package api

import (
	"database/sql"
	"net/http"

	"github.com/tenadam/api-gateway/config"
	"github.com/tenadam/api-gateway/internal/handler"
	"github.com/tenadam/api-gateway/internal/middleware"
	"github.com/tenadam/api-gateway/internal/repository"
	"github.com/tenadam/api-gateway/internal/service"
)

func NewRouter(cfg *config.Config, db *sql.DB) http.Handler {
	mux := http.NewServeMux()

	repos := repository.New(db)
	svcs := service.New(cfg, repos)
	h := handler.New(cfg, svcs)

	// Public
	mux.HandleFunc("GET /health", h.Health)
	mux.HandleFunc("POST /auth/register", h.PatientRegister)
	mux.HandleFunc("POST /auth/login", h.PatientLogin)
	mux.HandleFunc("POST /org/auth/register", h.OrgRegister)
	mux.HandleFunc("POST /org/auth/login", h.OrgLogin)
	mux.HandleFunc("POST /org/applications", h.OrgSubmitApplication)
	mux.HandleFunc("GET /org/hospitals", h.OrgListRegisteredHospitals)
	mux.HandleFunc("GET /organizations", h.OrgListOrganizations)

	// Patient protected
	mux.HandleFunc("GET /patients/me", h.RequirePatient(h.GetPatientMe))
	mux.HandleFunc("PUT /patients/update", h.RequirePatient(h.UpdatePatientMe))
	mux.HandleFunc("GET /doctors", h.RequirePatient(h.ListDoctors))
	mux.HandleFunc("GET /prescriptions", h.RequirePatient(h.ListPrescriptions))
	mux.HandleFunc("GET /patients/dashboard",h.RequirePatient(h.GetPatientDashboard))
	mux.HandleFunc("GET /lab-results", h.RequirePatient(h.ListLabResults))
	mux.HandleFunc("GET /billing/invoices", h.RequirePatient(h.ListInvoices))
	mux.HandleFunc("GET /insurance", h.RequirePatient(h.GetInsurance))
	mux.HandleFunc("GET /care/chronic", h.RequirePatient(h.ListChronicCare))
	mux.HandleFunc("GET /care/pregnancy", h.RequirePatient(h.ListPregnancyCare))
	mux.HandleFunc("GET /care/recurrent-medications", h.RequirePatient(h.ListRecurrentMedications))
	mux.HandleFunc("GET /messages", h.RequireAny(h.ListMessages))
	mux.HandleFunc("POST /messages", h.RequireAny(h.CreateMessage))
	mux.HandleFunc("GET /documents", h.RequirePatient(h.ListDocuments))
	mux.HandleFunc("POST /documents", h.RequirePatient(h.CreateDocument))
	mux.HandleFunc("GET /telemedicine/sessions", h.RequirePatient(h.ListTelemedicineSessions))
	mux.HandleFunc("POST /telemedicine/sessions", h.RequirePatient(h.CreateTelemedicineSession))
	mux.HandleFunc("POST /telemedicine/livekit/token", h.RequireAny(h.IssueLiveKitToken))
	mux.HandleFunc("GET /telemedicine/sessions/{id}/transcript-lines", h.RequireAny(h.ListTelemedicineTranscriptLines))
	mux.HandleFunc("POST /telemedicine/sessions/{id}/transcript-lines", h.RequireAny(h.CreateTelemedicineTranscriptLine))
	mux.HandleFunc("POST /telemedicine/sessions/{id}/summary", h.RequireAny(h.CreateTelemedicineSummary))
	mux.HandleFunc("GET /telemedicine/artifacts", h.RequirePatient(h.ListTelemedicineArtifacts))
	mux.HandleFunc("GET /pharmacy/medications", h.RequirePatient(h.ListPharmacyMedications))
	mux.HandleFunc("GET /pharmacy/pharmacies", h.RequirePatient(h.ListPharmacies))
	mux.HandleFunc("GET /pharmacy/orders", h.RequirePatient(h.ListPharmacyOrders))
	mux.HandleFunc("POST /pharmacy/orders", h.RequirePatient(h.CreatePharmacyOrder))
	mux.HandleFunc("GET /ai/consent", h.RequirePatient(h.GetAIConsent))
	mux.HandleFunc("PUT /ai/consent", h.RequirePatient(h.UpsertAIConsent))
	mux.HandleFunc("POST /ai/learning-samples", h.RequirePatient(h.CreateAILearningSample))
	mux.HandleFunc("POST /ai/router", h.RequirePatient(h.AIRouter))
	mux.HandleFunc("POST /appointments", h.RequireAny(h.CreateAppointment))
	mux.HandleFunc("GET /appointments", h.RequireAny(h.ListAppointments))
	mux.HandleFunc("GET /appointments/{id}", h.RequireAny(h.GetAppointment))
	mux.HandleFunc("PUT /appointments/{id}", h.RequireAny(h.UpdateAppointment))
	mux.HandleFunc("DELETE /appointments/{id}", h.RequireAny(h.DeleteAppointment))
	mux.HandleFunc("POST /appointments/{id}/assign", h.RequireOrgAnyRole("admin", "superadmin")(h.AssignAppointmentResources))
	mux.HandleFunc("GET /services", h.RequireAny(h.ListServices))
	mux.HandleFunc("POST /services", h.RequireOrgAnyRole("admin", "superadmin")(h.CreateService))
	mux.HandleFunc("PUT /services/{id}", h.RequireOrgAnyRole("admin", "superadmin")(h.UpdateService))
	mux.HandleFunc("DELETE /services/{id}", h.RequireOrgAnyRole("admin", "superadmin")(h.DeleteService))
	mux.HandleFunc("GET /resources", h.RequireOrgAnyRole("admin", "superadmin")(h.ListResources))
	mux.HandleFunc("GET /queues", h.RequireOrgAnyRole("admin", "doctor", "nurse", "staff", "superadmin")(h.ListQueues))
	mux.HandleFunc("POST /queues/reorder", h.RequireOrgAnyRole("admin", "doctor", "nurse", "staff", "superadmin")(h.ReorderQueue))
	mux.HandleFunc("POST /queues/check-in", h.RequireOrgAnyRole("admin", "doctor", "nurse", "staff", "superadmin")(h.CheckInQueue))

	// Org protected

	mux.HandleFunc("GET /org/me", h.RequireOrg(h.OrgMe))
	mux.HandleFunc("GET /org/me/telemedicine", h.RequireOrgAnyRole("doctor", "nurse")(h.OrgGetMyTelemedicineProfile))
	mux.HandleFunc("PATCH /org/me/telemedicine", h.RequireOrgAnyRole("doctor", "nurse")(h.OrgUpdateMyTelemedicineProfile))
	mux.HandleFunc("GET /org/configuration/me", h.RequireOrg(h.OrgGetMyOrganizationConfiguration))
	mux.HandleFunc("GET /org/service-management/me", h.RequireOrg(h.OrgGetMyServiceManagement))
	mux.HandleFunc("GET /org/application/me", h.RequireOrg(h.OrgMyApplication))
	mux.HandleFunc("GET /org/staff-role-templates", h.RequireOrgAnyRole("admin", "superadmin")(h.OrgListStaffRoleTemplates))
	mux.HandleFunc("POST /org/staff-role-templates", h.RequireOrgRole("superadmin")(h.OrgCreateStaffRoleTemplate))
	mux.HandleFunc("PUT /org/staff-role-templates/{key}", h.RequireOrgRole("superadmin")(h.OrgUpdateStaffRoleTemplate))
	mux.HandleFunc("PATCH /org/staff-role-templates/{key}/status", h.RequireOrgRole("superadmin")(h.OrgSetStaffRoleTemplateStatus))
	mux.HandleFunc("GET /org/applications", h.RequireOrgRole("superadmin")(h.OrgListApplications))
	mux.HandleFunc("GET /org/applications/{id}", h.RequireOrgRole("superadmin")(h.OrgGetApplication))
	mux.HandleFunc("PATCH /org/applications/{id}/approve", h.RequireOrgRole("superadmin")(h.OrgApproveApplication))
	mux.HandleFunc("PATCH /org/applications/{id}/reject", h.RequireOrgRole("superadmin")(h.OrgRejectApplication))
	mux.HandleFunc("PATCH /org/applications/{id}/services", h.RequireOrgRole("superadmin")(h.OrgConfigureApplicationServices))
	mux.HandleFunc("PATCH /org/applications/{id}/staff-configurations", h.RequireOrgRole("superadmin")(h.OrgSetApplicationStaffConfiguration))
	mux.HandleFunc("POST /org/applications/{id}/request-update", h.RequireOrgAnyRole("admin", "superadmin")(h.OrgRequestApplicationUpdate))
	mux.HandleFunc("PATCH /org/applications/{id}/resolve-update", h.RequireOrgRole("superadmin")(h.OrgResolveApplicationUpdate))
	mux.HandleFunc("PATCH /org/applications/{id}/domain", h.RequireOrgRole("superadmin")(h.OrgSetApplicationDomain))
	mux.HandleFunc("GET /org/organizations", h.RequireOrgRole("superadmin")(h.OrgListOrganizations))
	mux.HandleFunc("GET /org/tiers", h.RequireOrgRole("superadmin")(h.OrgListOrganizationTiers))
	mux.HandleFunc("GET /org/organizations/manage", h.RequireOrgRole("superadmin")(h.OrgListOrganizationsManaged))
	mux.HandleFunc("GET /org/organizations/{id}/configuration", h.RequireOrgAnyRole("admin", "superadmin")(h.OrgGetOrganizationConfiguration))
	mux.HandleFunc("PUT /org/organizations/{id}/configuration", h.RequireOrgAnyRole("admin", "superadmin")(h.OrgUpsertOrganizationConfiguration))
	mux.HandleFunc("GET /org/organizations/{id}/service-management", h.RequireOrgAnyRole("admin", "superadmin")(h.OrgGetOrganizationServiceManagement))
	mux.HandleFunc("PUT /org/organizations/{id}/service-management", h.RequireOrgAnyRole("admin", "superadmin")(h.OrgUpsertOrganizationServiceManagement))
	mux.HandleFunc("GET /org/organizations/{id}/staff", h.RequireOrgAnyRole("admin", "superadmin")(h.OrgListOrganizationStaff))
	mux.HandleFunc("POST /org/organizations/{id}/staff", h.RequireOrgAnyRole("admin", "superadmin")(h.OrgCreateOrganizationStaff))
	mux.HandleFunc("PUT /org/organizations/{id}/staff/{userId}", h.RequireOrgAnyRole("admin", "superadmin")(h.OrgUpdateOrganizationStaff))
	mux.HandleFunc("DELETE /org/organizations/{id}/staff/{userId}", h.RequireOrgAnyRole("admin", "superadmin")(h.OrgDeleteOrganizationStaff))
	mux.HandleFunc("GET /org/patients", h.RequireOrgAnyRole("admin", "doctor", "nurse", "staff", "superadmin")(h.OrgListPatients))
	mux.HandleFunc("GET /org/patients/{id}", h.RequireOrgAnyRole("admin", "doctor", "nurse", "staff", "superadmin")(h.OrgGetPatient))
	mux.HandleFunc("GET /org/users", h.RequireOrgRole("superadmin")(h.OrgListUsers))
	mux.HandleFunc("POST /org/users", h.RequireOrgRole("superadmin")(h.OrgCreateUser))
	mux.HandleFunc("PUT /org/users/{id}", h.RequireOrgRole("superadmin")(h.OrgUpdateUser))
	mux.HandleFunc("PUT /org/users/{id}/role", h.RequireOrgRole("superadmin")(h.OrgSetUserRole))
	mux.HandleFunc("PATCH /org/users/{id}/status", h.RequireOrgRole("superadmin")(h.OrgSetUserStatus))
	mux.HandleFunc("POST /org/users/{id}/reset-password", h.RequireOrgRole("superadmin")(h.OrgResetUserPassword))
	mux.HandleFunc("GET /org/system/overview", h.RequireOrgRole("superadmin")(h.OrgSystemOverview))
	mux.HandleFunc("GET /org/system/roles", h.RequireOrgRole("superadmin")(h.OrgListSystemRoles))
	mux.HandleFunc("GET /org/doctors", h.RequireOrgAnyRole("admin", "doctor", "nurse", "staff", "superadmin")(h.OrgListDoctors))
	mux.HandleFunc("POST /org/doctors", h.RequireOrgAnyRole("admin", "superadmin")(h.OrgCreateDoctor))
	mux.HandleFunc("GET /org/pharmacies", h.RequireOrgAnyRole("admin", "superadmin")(h.OrgListPharmacies))
	mux.HandleFunc("POST /org/pharmacies", h.RequireOrgAnyRole("admin", "superadmin")(h.OrgCreatePharmacy))
	mux.HandleFunc("GET /org/telemedicine/artifacts", h.RequireOrgAnyRole("admin", "doctor", "nurse", "staff", "superadmin")(h.OrgListTelemedicineArtifacts))
	mux.HandleFunc("GET /org/telemedicine/queue", h.RequireOrgAnyRole("admin", "doctor", "nurse", "superadmin")(h.OrgListTelemedicineQueue))
	mux.HandleFunc("POST /org/telemedicine/queue/accept", h.RequireOrgAnyRole("admin", "doctor", "nurse", "superadmin")(h.OrgAcceptTelemedicineSession))
	mux.HandleFunc("GET /org/ai/models", h.RequireOrgRole("superadmin")(h.ListAIModels))
	mux.HandleFunc("PUT /org/ai/models/status", h.RequireOrgRole("superadmin")(h.SetAIModelStatus))

	return middleware.CORS(cfg, mux)
}
