import type { FeatureFlagKey, RuleSeverity, ServiceKey, Tier } from "./types";

export const tierLabel: Record<Tier, string> = {
  "health-post": "Health Post",
  "health-center": "Health Center",
  "primary-hospital": "Primary Hospital",
  "general-specialized-hospital": "General/Specialized Hospital",
  "national-health-system": "National Health System",
};

export const tierOrder: Tier[] = [
  "health-post",
  "health-center",
  "primary-hospital",
  "general-specialized-hospital",
  "national-health-system",
];

export const serviceCatalog: Array<{
  key: ServiceKey;
  label: string;
  category:
    | "Core Clinical Services"
    | "Diagnostics"
    | "Pharmacy"
    | "Administration"
    | "Digital Services"
    | "System Configuration Impact";
}> = [
    { key: "patient_registration", label: "Patient registration", category: "Core Clinical Services" },
    { key: "encounter_capture", label: "Encounter capture", category: "Core Clinical Services" },
    { key: "condition_capture", label: "Condition capture", category: "Core Clinical Services" },
    { key: "referral_management", label: "Referral management", category: "Core Clinical Services" },
    { key: "referral_validation", label: "Referral validation", category: "Core Clinical Services" },
    { key: "immunization", label: "Immunization", category: "Core Clinical Services" },
    { key: "mch_anc_pnc", label: "MCH (ANC/PNC)", category: "Core Clinical Services" },
    { key: "mch_monitoring", label: "MCH monitoring", category: "Core Clinical Services" },
    { key: "nutrition_services", label: "Nutrition services", category: "Core Clinical Services" },
    { key: "emergency_detection", label: "Emergency detection", category: "Core Clinical Services" },
    { key: "reporting", label: "Reporting", category: "Administration" },
    { key: "longitudinal_care", label: "Longitudinal care", category: "Digital Services" },
    { key: "follow_up_tracking", label: "Follow-up tracking", category: "Digital Services" },
    { key: "basic_treatment", label: "Basic treatment", category: "Core Clinical Services" },
    { key: "disease_surveillance", label: "Disease surveillance", category: "Administration" },
    { key: "family_planning", label: "Family planning", category: "Core Clinical Services" },
    { key: "health_education", label: "Health education", category: "Core Clinical Services" },
    { key: "outreach", label: "Outreach", category: "Core Clinical Services" },
    { key: "outpatient_opd", label: "Outpatient (OPD)", category: "Core Clinical Services" },
    { key: "triage_services", label: "Triage services", category: "Core Clinical Services" },
    { key: "advanced_triage", label: "Advanced triage", category: "Core Clinical Services" },
    { key: "chronic_follow_up", label: "Chronic follow-up care", category: "Core Clinical Services" },
    { key: "emergency_care", label: "Emergency care", category: "Core Clinical Services" },
    { key: "inpatient_admission", label: "Inpatient admission", category: "Core Clinical Services" },
    { key: "inpatient_management", label: "Inpatient management", category: "Core Clinical Services" },
    { key: "delivery_service", label: "Delivery service", category: "Core Clinical Services" },
    { key: "trauma_care", label: "Trauma care", category: "Core Clinical Services" },
    { key: "emergency_response", label: "Emergency response", category: "Core Clinical Services" },
    { key: "resuscitation_tracking", label: "Resuscitation tracking", category: "Core Clinical Services" },
    { key: "continuous_monitoring", label: "Continuous monitoring", category: "Diagnostics" },
    { key: "discharge_preparation", label: "Discharge preparation", category: "Administration" },
    { key: "laboratory_services", label: "Laboratory services", category: "Diagnostics" },
    { key: "imaging_services", label: "Imaging services", category: "Diagnostics" },
    { key: "vital_signs_monitoring", label: "Vital signs monitoring", category: "Diagnostics" },
    { key: "specimen_collection", label: "Specimen collection", category: "Diagnostics" },
    { key: "lab_testing", label: "Lab testing", category: "Diagnostics" },
    { key: "result_reporting", label: "Result reporting", category: "Diagnostics" },
    { key: "sample_processing", label: "Sample processing", category: "Diagnostics" },
    { key: "result_validation", label: "Result validation", category: "Diagnostics" },
    { key: "specimen_processing", label: "Specimen processing", category: "Diagnostics" },
    { key: "data_upload", label: "Data upload", category: "Diagnostics" },
    { key: "image_interpretation", label: "Image interpretation", category: "Diagnostics" },
    { key: "report_validation", label: "Report validation", category: "Diagnostics" },
    { key: "genetic_testing", label: "Genetic testing", category: "Diagnostics" },
    { key: "histopathology", label: "Histopathology", category: "Diagnostics" },
    { key: "ct_mri_interpretation", label: "CT/MRI interpretation", category: "Diagnostics" },
    { key: "angiography_analysis", label: "Angiography analysis", category: "Diagnostics" },
    { key: "interventional_guidance", label: "Interventional guidance", category: "Diagnostics" },
    { key: "prescription_service", label: "Prescription service", category: "Pharmacy" },
    { key: "prescription_management", label: "Prescription management", category: "Pharmacy" },
    { key: "medication_dispensing", label: "Medication dispensing", category: "Pharmacy" },
    { key: "medication_counseling", label: "Medication counseling", category: "Pharmacy" },
    { key: "medication_administration", label: "Medication administration", category: "Pharmacy" },
    { key: "medication_reconciliation", label: "Medication reconciliation", category: "Pharmacy" },
    { key: "drug_interaction_check", label: "Drug interaction check", category: "Pharmacy" },
    { key: "drug_inventory_tracking", label: "Drug inventory tracking", category: "Pharmacy" },
    { key: "inventory_tracking", label: "Inventory tracking", category: "Pharmacy" },
    { key: "drug_dose_control", label: "Drug dose control", category: "Pharmacy" },
    { key: "icu_medication_control", label: "ICU medication control", category: "Pharmacy" },
    { key: "oncology_drugs", label: "Oncology drugs", category: "Pharmacy" },
    { key: "patient_flow", label: "Patient flow", category: "Administration" },
    { key: "appointment_scheduling", label: "Appointment scheduling", category: "Administration" },
    { key: "staff_management", label: "Staff management", category: "Administration" },
    { key: "user_management", label: "User management", category: "Administration" },
    { key: "service_config", label: "Service config", category: "Administration" },
    { key: "record_management", label: "Record management", category: "Administration" },
    { key: "data_quality_control", label: "Data quality control", category: "Administration" },
    { key: "document_management", label: "Document management", category: "Administration" },
    { key: "interoperability", label: "Interoperability", category: "Digital Services" },
    { key: "referral_oversight", label: "Referral oversight", category: "Administration" },
    { key: "document_exchange_oversight", label: "Document exchange oversight", category: "Administration" },
    { key: "billing", label: "Billing", category: "Administration" },
    { key: "financial_reporting", label: "Financial reporting", category: "Administration" },
    { key: "audit_monitoring", label: "Audit monitoring", category: "Administration" },
    { key: "referral_tracking", label: "Referral tracking", category: "Administration" },
    { key: "bed_management", label: "Bed management", category: "Administration" },
    { key: "scheduling", label: "Scheduling", category: "Administration" },
    { key: "discharge_summary", label: "Discharge summary", category: "Administration" },
    { key: "emr_access", label: "EMR access", category: "Digital Services" },
    { key: "patient_history_tracking", label: "Patient history tracking", category: "Digital Services" },
    { key: "digital_prescriptions", label: "Digital prescriptions", category: "Digital Services" },
    { key: "clinical_document_exchange", label: "Clinical document exchange", category: "Digital Services" },
    { key: "view_records", label: "View records", category: "Digital Services" },
    { key: "appointment_request", label: "Appointment request", category: "Digital Services" },
    { key: "notifications", label: "Notifications", category: "Digital Services" },
    { key: "consent_management", label: "Consent management", category: "Digital Services" },
    { key: "follow_up_compliance", label: "Follow-up compliance", category: "Digital Services" },
    { key: "symptom_analysis", label: "Symptom analysis", category: "Digital Services" },
    { key: "risk_scoring", label: "Risk scoring", category: "Digital Services" },
    { key: "prescription_draft", label: "Prescription draft", category: "Digital Services" },
    { key: "clinical_summary", label: "Clinical summary", category: "Digital Services" },
    { key: "decision_support", label: "Decision support", category: "Digital Services" },
    { key: "data_entry_assist", label: "Data entry assist", category: "Digital Services" },
    { key: "follow_up_prediction", label: "Follow-up prediction", category: "Digital Services" },
    { key: "offline_sync", label: "Offline sync", category: "Digital Services" },
    { key: "clinical_workflows_customization", label: "Custom clinical workflows", category: "System Configuration Impact" },
    { key: "ai_decision_support", label: "AI decision support", category: "System Configuration Impact" },
    { key: "advanced_case_management", label: "Advanced case management", category: "System Configuration Impact" },
    { key: "research_data_module", label: "Research data module", category: "System Configuration Impact" },
    { key: "cross_hospital_data_exchange", label: "Cross-hospital data exchange", category: "System Configuration Impact" },
    { key: "full_compliance_audit_tracking", label: "Full compliance and audit tracking", category: "System Configuration Impact" },
    { key: "diagnosis", label: "Diagnosis", category: "System Configuration Impact" },
    { key: "clinical_assessment", label: "Clinical assessment", category: "System Configuration Impact" },
    { key: "care_planning", label: "Care planning", category: "System Configuration Impact" },
    { key: "minor_procedures", label: "Minor procedures", category: "System Configuration Impact" },
    { key: "surgery_execution", label: "Surgery execution", category: "System Configuration Impact" },
    { key: "pre_op_planning", label: "Pre-op planning", category: "System Configuration Impact" },
    { key: "post_op_care", label: "Post-op care", category: "System Configuration Impact" },
    { key: "emergency_surgery", label: "Emergency surgery", category: "System Configuration Impact" },
    { key: "or_scheduling", label: "OR scheduling", category: "System Configuration Impact" },
    { key: "surgical_inventory", label: "Surgical inventory", category: "System Configuration Impact" },
    { key: "sterilization_workflow", label: "Sterilization workflow", category: "System Configuration Impact" },
    { key: "pre_op_assessment", label: "Pre-op assessment", category: "System Configuration Impact" },
    { key: "anesthesia_delivery", label: "Anesthesia delivery", category: "System Configuration Impact" },
    { key: "intra_op_monitoring", label: "Intra-op monitoring", category: "System Configuration Impact" },
    { key: "airway_management", label: "Airway management", category: "System Configuration Impact" },
    { key: "icu_handoff", label: "ICU handoff", category: "System Configuration Impact" },
    { key: "triage", label: "Triage", category: "System Configuration Impact" },
    { key: "admission_decision", label: "Admission decision", category: "System Configuration Impact" },
    { key: "mass_casualty_handling", label: "Mass casualty handling", category: "System Configuration Impact" },
    { key: "ventilator_management", label: "Ventilator management", category: "System Configuration Impact" },
    { key: "iv_infusion_control", label: "IV infusion control", category: "System Configuration Impact" },
    { key: "infection_control_logging", label: "Infection control logging", category: "System Configuration Impact" },
    { key: "or_optimization", label: "OR optimization", category: "System Configuration Impact" },
    { key: "icu_monitoring", label: "ICU monitoring", category: "System Configuration Impact" },
    { key: "complex_diagnosis", label: "Complex diagnosis", category: "System Configuration Impact" },
    { key: "specialist_consultation", label: "Specialist consultation", category: "System Configuration Impact" },
    { key: "advanced_care_planning", label: "Advanced care planning", category: "System Configuration Impact" },
    { key: "multidisciplinary_care", label: "Multidisciplinary care", category: "System Configuration Impact" },
    { key: "procedure_approval", label: "Procedure approval", category: "System Configuration Impact" },
    { key: "referral_acceptance", label: "Referral acceptance", category: "System Configuration Impact" },
    { key: "genetic_risk_stratification", label: "Genetic risk stratification", category: "System Configuration Impact" },
    { key: "oncology_protocols", label: "Oncology protocols", category: "System Configuration Impact" },
    { key: "icu_escalation_oversight", label: "ICU escalation oversight", category: "System Configuration Impact" },
    { key: "audit_clinical_governance", label: "Audit clinical governance", category: "System Configuration Impact" },
    { key: "transplant_surgery", label: "Transplant surgery", category: "System Configuration Impact" },
    { key: "surgical_planning", label: "Surgical planning", category: "System Configuration Impact" },
    { key: "post_op_management", label: "Post-op management", category: "System Configuration Impact" },
    { key: "icu_management", label: "ICU management", category: "System Configuration Impact" },
    { key: "ventilator_control", label: "Ventilator control", category: "System Configuration Impact" },
    { key: "hemodynamic_support", label: "Hemodynamic support", category: "System Configuration Impact" },
    { key: "multi_organ_failure_care", label: "Multi-organ failure care", category: "System Configuration Impact" },
    { key: "code_blue_leadership", label: "Code blue leadership", category: "System Configuration Impact" },
    { key: "icu_bed_allocation", label: "ICU bed allocation", category: "System Configuration Impact" },
    { key: "critical_risk_prediction", label: "Critical risk prediction", category: "System Configuration Impact" },
    { key: "draft_diagnosis", label: "Draft diagnosis", category: "System Configuration Impact" },
    { key: "care_plan_drafting", label: "Care plan drafting", category: "System Configuration Impact" },
    { key: "order_requests", label: "Order requests", category: "System Configuration Impact" },
    { key: "documentation", label: "Documentation", category: "System Configuration Impact" },
    { key: "data_entry", label: "Data entry", category: "System Configuration Impact" },
    { key: "procedure_assistance", label: "Procedure assistance", category: "System Configuration Impact" },
    { key: "oncology_care", label: "Oncology care", category: "System Configuration Impact" },
    { key: "dialysis_operation", label: "Dialysis operation", category: "System Configuration Impact" },
    { key: "device_management", label: "Device management", category: "System Configuration Impact" },
    { key: "advanced_diagnostics", label: "Advanced diagnostics", category: "Diagnostics" },
    { key: "teaching_rounds", label: "Teaching rounds", category: "System Configuration Impact" },
    { key: "skill_evaluation", label: "Skill evaluation", category: "System Configuration Impact" },
    { key: "clinical_trials", label: "Clinical trials", category: "System Configuration Impact" },
    { key: "patient_enrollment", label: "Patient enrollment", category: "System Configuration Impact" },
    { key: "data_analysis", label: "Data analysis", category: "System Configuration Impact" },
    { key: "icu_risk_prediction", label: "ICU risk prediction", category: "System Configuration Impact" },
    { key: "imaging_assistance", label: "Imaging assistance", category: "System Configuration Impact" },
    { key: "treatment_optimization", label: "Treatment optimization", category: "System Configuration Impact" },
    { key: "clinical_decision_support", label: "Clinical decision support", category: "System Configuration Impact" },
];

export const tierDefaultServices: Record<Tier, ServiceKey[]> = {
  "health-post": [
    "patient_registration",
      "encounter_capture",
      "condition_capture",
      "referral_management",
      "immunization",
      "mch_anc_pnc",
      "nutrition_services",
      "emergency_detection",
      "reporting",
      "longitudinal_care",
      "follow_up_tracking",
      "basic_treatment",
      "health_education",
      "outreach",
      "view_records",
      "appointment_request",
      "notifications",
      "consent_management",
  ],
  "health-center": [
      "outpatient_opd",
      "triage_services",
      "advanced_triage",
      "emergency_care",
      "chronic_follow_up",
      "follow_up_tracking",
      "vital_signs_monitoring",
    "outpatient_opd",
    "laboratory_services",
    "patient_registration",
    "appointment_scheduling",
    "referral_management",
      "referral_validation",
    "emr_access",
    "patient_history_tracking",
    "digital_prescriptions",
      "clinical_document_exchange",
      "record_management",
      "data_quality_control",
      "interoperability",
      "medication_dispensing",
      "prescription_service",
      "prescription_management",
      "drug_inventory_tracking",
    "full_compliance_audit_tracking",
      "audit_monitoring",
      "billing",
      "financial_reporting",
  ],
  "primary-hospital": [
    "outpatient_opd",
    "emergency_care",
    "inpatient_admission",
      "inpatient_management",
    "triage_services",
    "chronic_follow_up",
      "follow_up_tracking",
    "laboratory_services",
    "imaging_services",
      "specimen_collection",
      "lab_testing",
      "result_reporting",
      "sample_processing",
      "result_validation",
      "specimen_processing",
    "vital_signs_monitoring",
    "patient_registration",
    "appointment_scheduling",
    "referral_management",
      "referral_tracking",
    "emr_access",
    "patient_history_tracking",
    "digital_prescriptions",
      "clinical_document_exchange",
      "medication_reconciliation",
      "drug_interaction_check",
      "medication_administration",
      "medication_counseling",
    "clinical_workflows_customization",
    "advanced_case_management",
    "cross_hospital_data_exchange",
    "full_compliance_audit_tracking",
      "bed_management",
      "patient_flow",
      "scheduling",
      "staff_management",
      "billing",
      "financial_reporting",
      "audit_monitoring",
      "discharge_summary",
  ],
  "general-specialized-hospital": serviceCatalog.map((service) => service.key),
  "national-health-system": serviceCatalog.map((service) => service.key),
};

export const workflowDefaults: Record<
  string,
  {
    enabled: boolean;
    severity: RuleSeverity;
  }
> = {
  triage_before_consult: { enabled: true, severity: "strict" },
  mandatory_icd_coding: { enabled: true, severity: "strict" },
  prescription_approval: { enabled: false, severity: "flexible" },
  emergency_bypass: { enabled: true, severity: "flexible" },
};

export const commDefaults = {
  smsProvider: "Afromessage",
  emailSender: "alerts@tenadam.health",
  ussdGateway: "Ethio-Tel-USSD-1",
  notifyBySms: true,
  notifyByEmail: true,
};

export const billingDefaults = {
  enableBilling: true,
  enableInsurance: true,
  pricingModel: "fixed" as "fixed" | "dynamic",
  claimAutomation: true,
};

export const featureGroups: Array<{ title: string; keys: FeatureFlagKey[] }> = [
  { title: "Clinical Controls", keys: ["aiTriage", "clinicalDecisionSupport", "prescriptionValidation"] },
  { title: "Workflow Controls", keys: ["emergencyRouting", "referralEnforcement", "admissionApproval"] },
  { title: "Financial Controls", keys: ["billingSystem", "insuranceClaims", "discountWaivers", "pricingOverride"] },
  { title: "Communication Controls", keys: ["smsNotifications", "ussdAccess", "telemedicine", "patientPortalAccess"] },
  { title: "Platform & Compliance", keys: ["auditExport", "crossHospitalExchange", "researchDataModule", "advancedCaseManagement", "devSandbox"] },
];

export const featureFlagLabels: Record<FeatureFlagKey, string> = {
  aiTriage: "AI triage",
  telemedicine: "Telemedicine activation",
  emergencyRouting: "Emergency routing",
  auditExport: "Compliance audit export",
  devSandbox: "Developer sandbox",
  clinicalDecisionSupport: "Clinical decision support",
  prescriptionValidation: "Prescription validation rules",
  referralEnforcement: "Referral enforcement",
  admissionApproval: "Admission approval rules",
  billingSystem: "Billing system",
  insuranceClaims: "Insurance claims",
  discountWaivers: "Discounts and waivers",
  pricingOverride: "Service pricing override",
  smsNotifications: "SMS notifications",
  ussdAccess: "USSD access",
  patientPortalAccess: "Patient portal access",
  crossHospitalExchange: "Cross-hospital data exchange",
  researchDataModule: "Research data module",
  advancedCaseManagement: "Advanced case management",
};
