-- 016_restore_service_catalog.sql
-- Restore the expanded national service catalog and align tier defaults to canonical service keys.

WITH tenant AS (
    SELECT id FROM tenants WHERE slug = 'default' LIMIT 1
)
INSERT INTO services (
    tenant_id,
    name,
    description,
    service_category,
    service_type,
    active,
    duration_minutes,
    buffer_before_minutes,
    buffer_after_minutes,
    requires_appointment,
    allows_walkin,
    requires_checkin,
    supports_recurrence,
    allowed_patterns,
    max_occurrences
)
SELECT
    tenant.id,
    s.name,
    s.description,
    s.service_category,
    s.service_type,
    TRUE,
    s.duration_minutes,
    5,
    5,
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    '[]'::jsonb,
    NULL
FROM tenant
CROSS JOIN (
    VALUES
    ('Patient registration', 'Register or update patient identity data', 'Core Clinical Services', 'patient_registration', 15),
    ('Encounter capture', 'Record a clinical encounter', 'Core Clinical Services', 'encounter_capture', 15),
    ('Condition capture', 'Record a suspected or confirmed condition', 'Core Clinical Services', 'condition_capture', 15),
    ('Referral management', 'Create and manage referrals', 'Core Clinical Services', 'referral_management', 15),
    ('Referral validation', 'Validate referral details before escalation', 'Core Clinical Services', 'referral_validation', 15),
    ('Immunization', 'Immunization and vaccine recording', 'Core Clinical Services', 'immunization', 15),
    ('MCH (ANC/PNC)', 'Maternal and child health follow-up', 'Core Clinical Services', 'mch_anc_pnc', 20),
    ('MCH monitoring', 'Monitor maternal and neonatal progress', 'Core Clinical Services', 'mch_monitoring', 20),
    ('Nutrition services', 'Nutrition assessment and support', 'Core Clinical Services', 'nutrition_services', 15),
    ('Emergency detection', 'Detect danger signs and urgent cases', 'Core Clinical Services', 'emergency_detection', 15),
    ('Reporting', 'Daily and summary reporting', 'Administration', 'reporting', 15),
    ('Longitudinal care', 'Track ongoing patient cases', 'Digital Services', 'longitudinal_care', 15),
    ('Follow-up tracking', 'Track missed or scheduled follow-ups', 'Digital Services', 'follow_up_tracking', 15),
    ('Basic treatment', 'Basic treatment and medication support', 'Core Clinical Services', 'basic_treatment', 15),
    ('Disease surveillance', 'Suspected case surveillance and reporting', 'Administration', 'disease_surveillance', 15),
    ('Family planning', 'Family planning counseling and records', 'Core Clinical Services', 'family_planning', 15),
    ('Health education', 'Health education sessions and logs', 'Core Clinical Services', 'health_education', 15),
    ('Outreach', 'Community outreach and group visits', 'Core Clinical Services', 'outreach', 20),
    ('Outpatient (OPD)', 'Outpatient consultation service', 'Core Clinical Services', 'outpatient_opd', 20),
    ('Triage services', 'Routine triage and severity assessment', 'Core Clinical Services', 'triage_services', 15),
    ('Advanced triage', 'Expanded triage for higher acuity cases', 'Core Clinical Services', 'advanced_triage', 15),
    ('Chronic follow-up care', 'Chronic condition follow-up', 'Core Clinical Services', 'chronic_follow_up', 15),
    ('Emergency care', 'Emergency stabilization and urgent care', 'Core Clinical Services', 'emergency_care', 20),
    ('Inpatient admission', 'Admit a patient to inpatient care', 'Core Clinical Services', 'inpatient_admission', 20),
    ('Inpatient management', 'Ward and admission management', 'Core Clinical Services', 'inpatient_management', 20),
    ('Delivery service', 'Maternity and delivery support', 'Core Clinical Services', 'delivery_service', 20),
    ('Trauma care', 'Initial trauma assessment and care', 'Core Clinical Services', 'trauma_care', 20),
    ('Emergency response', 'Emergency response coordination', 'Core Clinical Services', 'emergency_response', 15),
    ('Resuscitation tracking', 'Track resuscitation and code-blue events', 'Core Clinical Services', 'resuscitation_tracking', 15),
    ('Continuous monitoring', 'Continuous patient monitoring', 'Diagnostics', 'continuous_monitoring', 15),
    ('Discharge preparation', 'Prepare discharge workflow and summary', 'Administration', 'discharge_preparation', 15),
    ('Laboratory services', 'General lab services', 'Diagnostics', 'laboratory_services', 20),
    ('Imaging services', 'General imaging services', 'Diagnostics', 'imaging_services', 20),
    ('Vital signs monitoring', 'Capture and monitor vital signs', 'Diagnostics', 'vital_signs_monitoring', 15),
    ('Specimen collection', 'Collect patient specimens', 'Diagnostics', 'specimen_collection', 15),
    ('Lab testing', 'Perform laboratory tests', 'Diagnostics', 'lab_testing', 20),
    ('Result reporting', 'Publish lab and diagnostic results', 'Diagnostics', 'result_reporting', 15),
    ('Sample processing', 'Process collected samples', 'Diagnostics', 'sample_processing', 15),
    ('Result validation', 'Validate test results', 'Diagnostics', 'result_validation', 15),
    ('Specimen processing', 'Process and label specimens', 'Diagnostics', 'specimen_processing', 15),
    ('Data upload', 'Upload diagnostic data', 'Diagnostics', 'data_upload', 15),
    ('Image interpretation', 'Interpret imaging studies', 'Diagnostics', 'image_interpretation', 20),
    ('Report validation', 'Validate diagnostic reports', 'Diagnostics', 'report_validation', 15),
    ('Genetic testing', 'Perform genetic testing workflows', 'Diagnostics', 'genetic_testing', 30),
    ('Histopathology', 'Tissue and pathology review', 'Diagnostics', 'histopathology', 30),
    ('CT/MRI interpretation', 'Interpret advanced imaging studies', 'Diagnostics', 'ct_mri_interpretation', 30),
    ('Angiography analysis', 'Analyze angiography studies', 'Diagnostics', 'angiography_analysis', 30),
    ('Interventional guidance', 'Support guided interventions', 'Diagnostics', 'interventional_guidance', 30),
    ('Prescription service', 'Generate prescriptions', 'Pharmacy', 'prescription_service', 15),
    ('Prescription management', 'Manage prescriptions and refills', 'Pharmacy', 'prescription_management', 15),
    ('Medication dispensing', 'Dispense medications', 'Pharmacy', 'medication_dispensing', 15),
    ('Medication counseling', 'Provide medication counseling', 'Pharmacy', 'medication_counseling', 15),
    ('Medication administration', 'Administer medications in care settings', 'Pharmacy', 'medication_administration', 15),
    ('Medication reconciliation', 'Review active medication lists', 'Pharmacy', 'medication_reconciliation', 15),
    ('Drug interaction check', 'Check for drug interactions', 'Pharmacy', 'drug_interaction_check', 15),
    ('Drug inventory tracking', 'Track medication stock and inventory', 'Pharmacy', 'drug_inventory_tracking', 15),
    ('Inventory tracking', 'Track inventory levels and use', 'Pharmacy', 'inventory_tracking', 15),
    ('Drug dose control', 'Control medication dosing', 'Pharmacy', 'drug_dose_control', 15),
    ('ICU medication control', 'Manage ICU medication dosing', 'Pharmacy', 'icu_medication_control', 20),
    ('Oncology drugs', 'Manage oncology medication workflows', 'Pharmacy', 'oncology_drugs', 20),
    ('Patient flow', 'Manage queue and patient flow', 'Administration', 'patient_flow', 15),
    ('Appointment scheduling', 'Schedule appointments', 'Administration', 'appointment_scheduling', 15),
    ('Staff management', 'Manage staff and templates', 'Administration', 'staff_management', 20),
    ('User management', 'Create and manage user accounts', 'Administration', 'user_management', 20),
    ('Service config', 'Configure service availability and state', 'Administration', 'service_config', 15),
    ('Record management', 'Manage records and archives', 'Administration', 'record_management', 20),
    ('Data quality control', 'Validate and clean data', 'Administration', 'data_quality_control', 15),
    ('Document management', 'Manage clinical documents', 'Administration', 'document_management', 15),
    ('Interoperability', 'Exchange data with external systems', 'Digital Services', 'interoperability', 20),
    ('Referral oversight', 'Monitor referral processes', 'Administration', 'referral_oversight', 15),
    ('Document exchange oversight', 'Review clinical document transfers', 'Administration', 'document_exchange_oversight', 15),
    ('Billing', 'Billing and claims intake', 'Administration', 'billing', 20),
    ('Financial reporting', 'Generate financial reports', 'Administration', 'financial_reporting', 20),
    ('Audit monitoring', 'Monitor audit and compliance logs', 'Administration', 'audit_monitoring', 15),
    ('Referral tracking', 'Track referral status', 'Administration', 'referral_tracking', 15),
    ('Bed management', 'Assign and manage beds', 'Administration', 'bed_management', 15),
    ('Scheduling', 'Schedule resource and service slots', 'Administration', 'scheduling', 15),
    ('Discharge summary', 'Generate discharge summaries', 'Administration', 'discharge_summary', 15),
    ('EMR access', 'Access electronic medical records', 'Digital Services', 'emr_access', 15),
    ('Patient history tracking', 'Track patient history over time', 'Digital Services', 'patient_history_tracking', 15),
    ('Digital prescriptions', 'Issue digital prescriptions', 'Digital Services', 'digital_prescriptions', 15),
    ('Clinical document exchange', 'Share clinical documents between services', 'Digital Services', 'clinical_document_exchange', 15),
    ('View records', 'Read patient records', 'Digital Services', 'view_records', 15),
    ('Appointment request', 'Request appointments digitally', 'Digital Services', 'appointment_request', 15),
    ('Notifications', 'Receive system notifications', 'Digital Services', 'notifications', 15),
    ('Consent management', 'Manage consent records', 'Digital Services', 'consent_management', 15),
    ('Follow-up compliance', 'Track follow-up attendance and confirmation', 'Digital Services', 'follow_up_compliance', 15),
    ('Symptom analysis', 'Analyze patient symptoms', 'Digital Services', 'symptom_analysis', 15),
    ('Risk scoring', 'Score clinical risk', 'Digital Services', 'risk_scoring', 15),
    ('Prescription draft', 'Draft medication prescriptions', 'Digital Services', 'prescription_draft', 15),
    ('Clinical summary', 'Generate clinical summaries', 'Digital Services', 'clinical_summary', 15),
    ('Decision support', 'Support clinical decisions', 'Digital Services', 'decision_support', 15),
    ('Data entry assist', 'Assist with structured data entry', 'Digital Services', 'data_entry_assist', 15),
    ('Follow-up prediction', 'Predict follow-up dropouts', 'Digital Services', 'follow_up_prediction', 15),
    ('Offline sync', 'Synchronize offline records', 'Digital Services', 'offline_sync', 15),
    ('Custom clinical workflows', 'Configure custom clinical workflows', 'System Configuration Impact', 'clinical_workflows_customization', 20),
    ('AI decision support', 'Configure AI decision support', 'System Configuration Impact', 'ai_decision_support', 20),
    ('Advanced case management', 'Support advanced case management', 'System Configuration Impact', 'advanced_case_management', 20),
    ('Research data module', 'Enable research data workflows', 'System Configuration Impact', 'research_data_module', 20),
    ('Cross-hospital data exchange', 'Exchange data across hospitals', 'System Configuration Impact', 'cross_hospital_data_exchange', 20),
    ('Full compliance and audit tracking', 'Full audit and compliance tracking', 'System Configuration Impact', 'full_compliance_audit_tracking', 20),
    ('Diagnosis', 'Clinical diagnosis workflow', 'System Configuration Impact', 'diagnosis', 20),
    ('Clinical assessment', 'Structured clinical assessment', 'System Configuration Impact', 'clinical_assessment', 20),
    ('Care planning', 'Create and manage care plans', 'System Configuration Impact', 'care_planning', 20),
    ('Minor procedures', 'Perform minor procedures', 'System Configuration Impact', 'minor_procedures', 20),
    ('Surgery execution', 'Execute surgical procedures', 'System Configuration Impact', 'surgery_execution', 30),
    ('Pre-op planning', 'Prepare pre-operative plan', 'System Configuration Impact', 'pre_op_planning', 20),
    ('Post-op care', 'Manage postoperative care', 'System Configuration Impact', 'post_op_care', 20),
    ('Emergency surgery', 'Support emergency surgery workflows', 'System Configuration Impact', 'emergency_surgery', 30),
    ('OR scheduling', 'Schedule operating room usage', 'System Configuration Impact', 'or_scheduling', 20),
    ('Surgical inventory', 'Track surgical inventory', 'System Configuration Impact', 'surgical_inventory', 20),
    ('Sterilization workflow', 'Manage sterilization workflow', 'System Configuration Impact', 'sterilization_workflow', 20),
    ('Pre-op assessment', 'Perform pre-operative assessment', 'System Configuration Impact', 'pre_op_assessment', 20),
    ('Anesthesia delivery', 'Deliver anesthesia', 'System Configuration Impact', 'anesthesia_delivery', 20),
    ('Intra-op monitoring', 'Monitor intra-operative status', 'System Configuration Impact', 'intra_op_monitoring', 20),
    ('Airway management', 'Manage airway during procedures', 'System Configuration Impact', 'airway_management', 20),
    ('ICU handoff', 'Coordinate ICU handoff', 'System Configuration Impact', 'icu_handoff', 15),
    ('Triage', 'Triage and prioritize patients', 'System Configuration Impact', 'triage', 15),
    ('Admission decision', 'Decide on admission or discharge', 'System Configuration Impact', 'admission_decision', 15),
    ('Mass casualty handling', 'Handle mass casualty incidents', 'System Configuration Impact', 'mass_casualty_handling', 20),
    ('Ventilator management', 'Manage ventilator workflows', 'System Configuration Impact', 'ventilator_management', 20),
    ('IV infusion control', 'Control IV infusions', 'System Configuration Impact', 'iv_infusion_control', 15),
    ('Infection control logging', 'Log infection control activity', 'System Configuration Impact', 'infection_control_logging', 15),
    ('OR optimization', 'Optimize OR utilization', 'System Configuration Impact', 'or_optimization', 15),
    ('ICU monitoring', 'Monitor ICU workflows', 'System Configuration Impact', 'icu_monitoring', 15),
    ('Complex diagnosis', 'Support complex diagnosis workflows', 'System Configuration Impact', 'complex_diagnosis', 20),
    ('Specialist consultation', 'Specialist consultation workflow', 'System Configuration Impact', 'specialist_consultation', 20),
    ('Advanced care planning', 'Advanced care planning', 'System Configuration Impact', 'advanced_care_planning', 20),
    ('Multidisciplinary care', 'Coordinate multidisciplinary care', 'System Configuration Impact', 'multidisciplinary_care', 20),
    ('Procedure approval', 'Approve or deny procedures', 'System Configuration Impact', 'procedure_approval', 15),
    ('Referral acceptance', 'Accept incoming referrals', 'System Configuration Impact', 'referral_acceptance', 15),
    ('Genetic risk stratification', 'Stratify genetic risk', 'System Configuration Impact', 'genetic_risk_stratification', 20),
    ('Oncology protocols', 'Manage oncology protocols', 'System Configuration Impact', 'oncology_protocols', 20),
    ('ICU escalation oversight', 'Oversee ICU escalation', 'System Configuration Impact', 'icu_escalation_oversight', 15),
    ('Audit clinical governance', 'Audit clinical governance workflows', 'System Configuration Impact', 'audit_clinical_governance', 15),
    ('Transplant surgery', 'Support transplant surgery', 'System Configuration Impact', 'transplant_surgery', 30),
    ('Surgical planning', 'Plan surgical workflows', 'System Configuration Impact', 'surgical_planning', 20),
    ('Post-op management', 'Manage postoperative recovery', 'System Configuration Impact', 'post_op_management', 20),
    ('ICU management', 'Manage ICU care', 'System Configuration Impact', 'icu_management', 20),
    ('Ventilator control', 'Control ventilator settings', 'System Configuration Impact', 'ventilator_control', 15),
    ('Hemodynamic support', 'Support hemodynamic stability', 'System Configuration Impact', 'hemodynamic_support', 20),
    ('Multi-organ failure care', 'Coordinate multi-organ failure care', 'System Configuration Impact', 'multi_organ_failure_care', 20),
    ('Code blue leadership', 'Lead code blue response', 'System Configuration Impact', 'code_blue_leadership', 15),
    ('ICU bed allocation', 'Allocate ICU beds', 'System Configuration Impact', 'icu_bed_allocation', 15),
    ('Critical risk prediction', 'Predict critical deterioration risk', 'System Configuration Impact', 'critical_risk_prediction', 15),
    ('Draft diagnosis', 'Draft diagnosis for supervised review', 'System Configuration Impact', 'draft_diagnosis', 15),
    ('Care plan drafting', 'Draft care plans', 'System Configuration Impact', 'care_plan_drafting', 15),
    ('Order requests', 'Request diagnostic and clinical orders', 'System Configuration Impact', 'order_requests', 15),
    ('Documentation', 'Clinical documentation workflow', 'System Configuration Impact', 'documentation', 15),
    ('Data entry', 'Structured data entry', 'System Configuration Impact', 'data_entry', 15),
    ('Procedure assistance', 'Assist procedural workflows', 'System Configuration Impact', 'procedure_assistance', 15),
    ('Oncology care', 'Support oncology care', 'System Configuration Impact', 'oncology_care', 20),
    ('Dialysis operation', 'Support dialysis operations', 'System Configuration Impact', 'dialysis_operation', 20),
    ('Device management', 'Manage clinical devices', 'System Configuration Impact', 'device_management', 20),
    ('Teaching rounds', 'Manage teaching rounds', 'System Configuration Impact', 'teaching_rounds', 15),
    ('Skill evaluation', 'Evaluate learner skills', 'System Configuration Impact', 'skill_evaluation', 15),
    ('Clinical trials', 'Clinical trial support', 'System Configuration Impact', 'clinical_trials', 20),
    ('Patient enrollment', 'Enroll patients into studies', 'System Configuration Impact', 'patient_enrollment', 15),
    ('Data analysis', 'Analyze clinical data', 'System Configuration Impact', 'data_analysis', 15),
    ('ICU risk prediction', 'Predict ICU risk', 'System Configuration Impact', 'icu_risk_prediction', 15),
    ('Imaging assistance', 'Assist imaging interpretation', 'System Configuration Impact', 'imaging_assistance', 15),
    ('Treatment optimization', 'Optimize treatment plans', 'System Configuration Impact', 'treatment_optimization', 15),
    ('Clinical decision support', 'Clinical decision support workflows', 'System Configuration Impact', 'clinical_decision_support', 15)
) AS s(name, description, service_category, service_type, duration_minutes)
ON CONFLICT (tenant_id, service_type) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    service_category = EXCLUDED.service_category,
    active = TRUE,
    duration_minutes = EXCLUDED.duration_minutes,
    updated_at = NOW();

INSERT INTO organization_tier_requirements (tier, description, min_staff, default_services)
VALUES
    (
        'health-post',
        'Tier 1 PHCU level focused on community prevention and basic care.',
        '{"community-health-worker":2,"nurse":1,"midwife":1,"support":1}'::jsonb,
        '["patient_registration","encounter_capture","condition_capture","referral_management","immunization","mch_anc_pnc","nutrition_services","emergency_detection","reporting","longitudinal_care","follow_up_tracking","basic_treatment","health_education","outreach","view_records","appointment_request","notifications","consent_management"]'::jsonb
    ),
    (
        'health-center',
        'Tier 2 PHCU hub with outpatient, diagnostics, pharmacy, and referral management.',
        '{"admin":1,"finance":1,"doctor":1,"health-officer":2,"nurse":4,"midwife":2,"lab":2,"pharmacist":1,"reception":2}'::jsonb,
        '["outpatient_opd","triage_services","advanced_triage","emergency_care","chronic_follow_up","follow_up_tracking","laboratory_services","specimen_collection","lab_testing","result_reporting","sample_processing","result_validation","patient_registration","appointment_scheduling","referral_management","referral_validation","emr_access","patient_history_tracking","digital_prescriptions","clinical_document_exchange","record_management","data_quality_control","interoperability","medication_dispensing","prescription_service","prescription_management","drug_inventory_tracking","audit_monitoring","billing","financial_reporting"]'::jsonb
    ),
    (
        'primary-hospital',
        'Tier 3 hospital with inpatient, surgery, and expanded diagnostics.',
        '{"admin":2,"finance":2,"doctor":4,"surgeon":2,"obgyn":1,"nurse":10,"icu-nurse":2,"lab":3,"radiology":2,"pharmacist":2,"reception":3}'::jsonb,
        '["outpatient_opd","emergency_care","inpatient_admission","inpatient_management","triage_services","chronic_follow_up","follow_up_tracking","laboratory_services","imaging_services","specimen_collection","lab_testing","result_reporting","sample_processing","result_validation","patient_registration","appointment_scheduling","referral_management","referral_tracking","emr_access","patient_history_tracking","digital_prescriptions","clinical_document_exchange","medication_reconciliation","drug_interaction_check","medication_administration","medication_counseling","bed_management","patient_flow","scheduling","staff_management","billing","financial_reporting","audit_monitoring","discharge_summary"]'::jsonb
    ),
    (
        'general-specialized-hospital',
        'Tier 4 general and specialized tertiary care with advanced clinical workflows.',
        '{"admin":3,"finance":3,"consultant":8,"specialist":12,"resident":10,"nurse":25,"icu-nurse":8,"lab":6,"radiology":5,"pharmacist":4,"reception":5,"it":3}'::jsonb,
        '["outpatient_opd","emergency_care","inpatient_admission","inpatient_management","triage_services","advanced_triage","chronic_follow_up","follow_up_tracking","laboratory_services","imaging_services","specimen_collection","lab_testing","result_reporting","sample_processing","result_validation","patient_registration","appointment_scheduling","referral_management","referral_validation","emr_access","patient_history_tracking","digital_prescriptions","clinical_document_exchange","advanced_case_management","cross_hospital_data_exchange","full_compliance_audit_tracking","medication_reconciliation","drug_interaction_check","medication_administration","medication_counseling","bed_management","patient_flow","scheduling","staff_management","billing","financial_reporting","audit_monitoring","discharge_summary","diagnosis","clinical_assessment","care_planning","or_scheduling","surgical_inventory","anesthesia_delivery","intra_op_monitoring","icu_management","ventilator_control","hemodynamic_support","multi_organ_failure_care"]'::jsonb
    ),
    (
        'national-health-system',
        'Tier 5 national oversight and interoperability governance layer.',
        '{"system-admin":3,"health-informatics":6,"policy":4,"compliance":4,"data-analyst":6}'::jsonb,
        '["outpatient_opd","emergency_care","inpatient_admission","inpatient_management","triage_services","advanced_triage","chronic_follow_up","follow_up_tracking","laboratory_services","imaging_services","specimen_collection","lab_testing","result_reporting","sample_processing","result_validation","patient_registration","appointment_scheduling","referral_management","referral_validation","emr_access","patient_history_tracking","digital_prescriptions","clinical_document_exchange","advanced_case_management","cross_hospital_data_exchange","full_compliance_audit_tracking","research_data_module","clinical_workflows_customization","ai_decision_support","record_management","data_quality_control","interoperability","audit_monitoring","financial_reporting","billing","bed_management","patient_flow","scheduling","staff_management","view_records","consent_management","decision_support","clinical_decision_support","clinical_trials","patient_enrollment","data_analysis"]'::jsonb
    )
ON CONFLICT (tier) DO UPDATE SET
    description = EXCLUDED.description,
    min_staff = EXCLUDED.min_staff,
    default_services = EXCLUDED.default_services,
    updated_at = NOW();