-- 017_seed_full_hospital_staff_templates.sql
-- Seed standardized EMR staff templates into staff_role_templates.

INSERT INTO staff_role_templates (template_key, title, role_group, category, api_role, description, sort_order, active)
VALUES
  ('governance-executive-leadership-board-of-directors', 'Board of Directors', 'Administrative Staff', 'Governance & Executive Leadership', 'admin', 'Standardized EMR role template', 1, TRUE),
  ('governance-executive-leadership-trustees', 'Trustees', 'Administrative Staff', 'Governance & Executive Leadership', 'admin', 'Standardized EMR role template', 2, TRUE),
  ('governance-executive-leadership-hospital-owners', 'Hospital Owners', 'Administrative Staff', 'Governance & Executive Leadership', 'admin', 'Standardized EMR role template', 3, TRUE),
  ('governance-executive-leadership-chief-executive-officer', 'Chief Executive Officer (CEO)', 'Administrative Staff', 'Governance & Executive Leadership', 'admin', 'Standardized EMR role template', 4, TRUE),
  ('governance-executive-leadership-chief-operating-officer', 'Chief Operating Officer (COO)', 'Administrative Staff', 'Governance & Executive Leadership', 'admin', 'Standardized EMR role template', 5, TRUE),
  ('governance-executive-leadership-chief-medical-officer', 'Chief Medical Officer (CMO)', 'Clinical Staff', 'Governance & Executive Leadership', 'doctor', 'Standardized EMR role template', 6, TRUE),
  ('governance-executive-leadership-chief-nursing-officer', 'Chief Nursing Officer (CNO)', 'Nursing Staff', 'Governance & Executive Leadership', 'nurse', 'Standardized EMR role template', 7, TRUE),
  ('governance-executive-leadership-chief-financial-officer', 'Chief Financial Officer (CFO)', 'Administrative Staff', 'Governance & Executive Leadership', 'admin', 'Standardized EMR role template', 8, TRUE),
  ('governance-executive-leadership-chief-information-officer', 'Chief Information Officer (CIO)', 'IT & System', 'Governance & Executive Leadership', 'admin', 'Standardized EMR role template', 9, TRUE),
  ('governance-executive-leadership-chief-technology-officer', 'Chief Technology Officer (CTO)', 'IT & System', 'Governance & Executive Leadership', 'admin', 'Standardized EMR role template', 10, TRUE),
  ('governance-executive-leadership-chief-human-resources-officer', 'Chief Human Resources Officer (CHRO)', 'Administrative Staff', 'Governance & Executive Leadership', 'admin', 'Standardized EMR role template', 11, TRUE),
  ('governance-executive-leadership-chief-compliance-officer', 'Chief Compliance Officer', 'Administrative Staff', 'Governance & Executive Leadership', 'admin', 'Standardized EMR role template', 12, TRUE),
  ('medical-staff-medical-director', 'Medical Director', 'Clinical Staff', 'Medical Staff', 'doctor', 'Standardized EMR role template', 13, TRUE),
  ('medical-staff-department-head-hod', 'Department Head (HOD)', 'Clinical Staff', 'Medical Staff', 'doctor', 'Standardized EMR role template', 14, TRUE),
  ('medical-staff-general-practitioner-gp', 'General Practitioner (GP)', 'Clinical Staff', 'Medical Staff', 'doctor', 'Standardized EMR role template', 15, TRUE),
  ('medical-staff-attending-physician', 'Attending Physician', 'Clinical Staff', 'Medical Staff', 'doctor', 'Standardized EMR role template', 16, TRUE),
  ('medical-staff-consultant-specialist', 'Consultant (Specialist)', 'Clinical Staff', 'Medical Staff', 'doctor', 'Standardized EMR role template', 17, TRUE),
  ('medical-staff-registrar', 'Registrar', 'Clinical Staff', 'Medical Staff', 'doctor', 'Standardized EMR role template', 18, TRUE),
  ('medical-staff-resident', 'Resident', 'Clinical Staff', 'Medical Staff', 'doctor', 'Standardized EMR role template', 19, TRUE),
  ('medical-staff-intern', 'Intern', 'Clinical Staff', 'Medical Staff', 'doctor', 'Standardized EMR role template', 20, TRUE),
  ('medical-staff-medical-student', 'Medical Student', 'Clinical Staff', 'Medical Staff', 'staff', 'Standardized EMR role template', 21, TRUE),
  ('medical-specialties-cardiologist', 'Cardiologist', 'Clinical Staff', 'Medical Specialties', 'doctor', 'Standardized EMR role template', 22, TRUE),
  ('medical-specialties-neurologist', 'Neurologist', 'Clinical Staff', 'Medical Specialties', 'doctor', 'Standardized EMR role template', 23, TRUE),
  ('medical-specialties-dermatologist', 'Dermatologist', 'Clinical Staff', 'Medical Specialties', 'doctor', 'Standardized EMR role template', 24, TRUE),
  ('medical-specialties-pediatrician', 'Pediatrician', 'Clinical Staff', 'Medical Specialties', 'doctor', 'Standardized EMR role template', 25, TRUE),
  ('medical-specialties-psychiatrist', 'Psychiatrist', 'Clinical Staff', 'Medical Specialties', 'doctor', 'Standardized EMR role template', 26, TRUE),
  ('medical-specialties-oncologist', 'Oncologist', 'Clinical Staff', 'Medical Specialties', 'doctor', 'Standardized EMR role template', 27, TRUE),
  ('medical-specialties-endocrinologist', 'Endocrinologist', 'Clinical Staff', 'Medical Specialties', 'doctor', 'Standardized EMR role template', 28, TRUE),
  ('medical-specialties-gastroenterologist', 'Gastroenterologist', 'Clinical Staff', 'Medical Specialties', 'doctor', 'Standardized EMR role template', 29, TRUE),
  ('medical-specialties-pulmonologist', 'Pulmonologist', 'Clinical Staff', 'Medical Specialties', 'doctor', 'Standardized EMR role template', 30, TRUE),
  ('medical-specialties-nephrologist', 'Nephrologist', 'Clinical Staff', 'Medical Specialties', 'doctor', 'Standardized EMR role template', 31, TRUE),
  ('medical-specialties-infectious-disease-specialist', 'Infectious Disease Specialist', 'Clinical Staff', 'Medical Specialties', 'doctor', 'Standardized EMR role template', 32, TRUE),
  ('medical-specialties-emergency-medicine-physician', 'Emergency Medicine Physician', 'Clinical Staff', 'Medical Specialties', 'doctor', 'Standardized EMR role template', 33, TRUE),
  ('surgical-staff-general-surgeon', 'General Surgeon', 'Clinical Staff', 'Surgical Staff', 'doctor', 'Standardized EMR role template', 34, TRUE),
  ('surgical-staff-orthopedic-surgeon', 'Orthopedic Surgeon', 'Clinical Staff', 'Surgical Staff', 'doctor', 'Standardized EMR role template', 35, TRUE),
  ('surgical-staff-neurosurgeon', 'Neurosurgeon', 'Clinical Staff', 'Surgical Staff', 'doctor', 'Standardized EMR role template', 36, TRUE),
  ('surgical-staff-cardiothoracic-surgeon', 'Cardiothoracic Surgeon', 'Clinical Staff', 'Surgical Staff', 'doctor', 'Standardized EMR role template', 37, TRUE),
  ('surgical-staff-plastic-surgeon', 'Plastic Surgeon', 'Clinical Staff', 'Surgical Staff', 'doctor', 'Standardized EMR role template', 38, TRUE),
  ('surgical-staff-urologist', 'Urologist', 'Clinical Staff', 'Surgical Staff', 'doctor', 'Standardized EMR role template', 39, TRUE),
  ('surgical-staff-obstetrician-gynecologist-ob-gyn', 'Obstetrician/Gynecologist (OB/GYN)', 'Clinical Staff', 'Surgical Staff', 'doctor', 'Standardized EMR role template', 40, TRUE),
  ('procedure-based-specialists-anesthesiologist', 'Anesthesiologist', 'Clinical Staff', 'Procedure-Based Specialists', 'doctor', 'Standardized EMR role template', 41, TRUE),
  ('procedure-based-specialists-intensivist-icu', 'Intensivist (ICU)', 'Clinical Staff', 'Procedure-Based Specialists', 'doctor', 'Standardized EMR role template', 42, TRUE),
  ('procedure-based-specialists-radiologist', 'Radiologist', 'Diagnostic Staff', 'Procedure-Based Specialists', 'doctor', 'Standardized EMR role template', 43, TRUE),
  ('procedure-based-specialists-pathologist', 'Pathologist', 'Diagnostic Staff', 'Procedure-Based Specialists', 'doctor', 'Standardized EMR role template', 44, TRUE),
  ('nursing-staff-director-of-nursing', 'Director of Nursing', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 45, TRUE),
  ('nursing-staff-nurse-unit-manager-ward-manager', 'Nurse Unit Manager (Ward Manager)', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 46, TRUE),
  ('nursing-staff-assistant-nurse-manager', 'Assistant Nurse Manager', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 47, TRUE),
  ('nursing-staff-registered-nurse-rn', 'Registered Nurse (RN)', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 48, TRUE),
  ('nursing-staff-enrolled-nurse', 'Enrolled Nurse', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 49, TRUE),
  ('nursing-staff-licensed-practical-nurse-lpn', 'Licensed Practical Nurse (LPN)', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 50, TRUE),
  ('nursing-staff-icu-nurse', 'ICU Nurse', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 51, TRUE),
  ('nursing-staff-emergency-triage-nurse', 'Emergency/Triage Nurse', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 52, TRUE),
  ('nursing-staff-surgical-nurse', 'Surgical Nurse', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 53, TRUE),
  ('nursing-staff-pediatric-nurse', 'Pediatric Nurse', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 54, TRUE),
  ('nursing-staff-oncology-nurse', 'Oncology Nurse', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 55, TRUE),
  ('nursing-staff-dialysis-nurse', 'Dialysis Nurse', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 56, TRUE),
  ('nursing-staff-infection-control-nurse', 'Infection Control Nurse', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 57, TRUE),
  ('nursing-staff-psychiatric-nurse', 'Psychiatric Nurse', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 58, TRUE),
  ('nursing-staff-community-health-nurse', 'Community Health Nurse', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 59, TRUE),
  ('nursing-staff-midwife', 'Midwife', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 60, TRUE),
  ('nursing-staff-nurse-practitioner-np', 'Nurse Practitioner (NP)', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 61, TRUE),
  ('nursing-staff-clinical-nurse-specialist', 'Clinical Nurse Specialist', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 62, TRUE),
  ('nursing-staff-nurse-educator', 'Nurse Educator', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 63, TRUE),
  ('nursing-staff-nurse-researcher', 'Nurse Researcher', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 64, TRUE),
  ('nursing-staff-ward-nurse', 'Ward Nurse', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 65, TRUE),
  ('nursing-staff-charge-nurse', 'Charge Nurse', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 66, TRUE),
  ('nursing-staff-bedside-nurse', 'Bedside Nurse', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 67, TRUE),
  ('nursing-staff-nurse-assistant-nursing-aide', 'Nurse Assistant / Nursing Aide', 'Nursing Staff', 'Nursing Staff', 'staff', 'Standardized EMR role template', 68, TRUE),
  ('allied-health-professionals-physiotherapist', 'Physiotherapist', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 69, TRUE),
  ('allied-health-professionals-occupational-therapist', 'Occupational Therapist', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 70, TRUE),
  ('allied-health-professionals-speech-language-therapist', 'Speech & Language Therapist', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 71, TRUE),
  ('allied-health-professionals-respiratory-therapist', 'Respiratory Therapist', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 72, TRUE),
  ('allied-health-professionals-dietitian', 'Dietitian', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 73, TRUE),
  ('allied-health-professionals-nutritionist', 'Nutritionist', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 74, TRUE),
  ('allied-health-professionals-pharmacist', 'Pharmacist', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 75, TRUE),
  ('allied-health-professionals-clinical-pharmacist', 'Clinical Pharmacist', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 76, TRUE),
  ('allied-health-professionals-pharmacy-technician', 'Pharmacy Technician', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 77, TRUE),
  ('allied-health-professionals-pharmacy-assistant', 'Pharmacy Assistant', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 78, TRUE),
  ('allied-health-professionals-psychologist', 'Psychologist', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 79, TRUE),
  ('allied-health-professionals-social-worker', 'Social Worker', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 80, TRUE)
ON CONFLICT (template_key) DO UPDATE
SET
  title = EXCLUDED.title,
  role_group = EXCLUDED.role_group,
  category = EXCLUDED.category,
  api_role = EXCLUDED.api_role,
  description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order,
  active = TRUE,
  updated_at = NOW();
