-- 018_expand_full_hospital_staff_templates_to_154.sql
-- Expand standardized EMR staff templates to the canonical 154-role master list.

INSERT INTO staff_role_templates (template_key, title, role_group, category, api_role, description, sort_order, active)
VALUES
  ('governance-executive-leadership-board-of-directors', 'Board of Directors', 'Administrative Staff', 'Governance & Executive Leadership', 'admin', 'Standardized EMR role template', 1, TRUE),
  ('governance-executive-leadership-trustees', 'Trustees', 'Administrative Staff', 'Governance & Executive Leadership', 'admin', 'Standardized EMR role template', 2, TRUE),
  ('governance-executive-leadership-hospital-owners', 'Hospital Owners', 'Administrative Staff', 'Governance & Executive Leadership', 'admin', 'Standardized EMR role template', 3, TRUE),
  ('governance-executive-leadership-chief-executive-officer', 'Chief Executive Officer (CEO)', 'Administrative Staff', 'Governance & Executive Leadership', 'admin', 'Standardized EMR role template', 4, TRUE),
  ('governance-executive-leadership-chief-operating-officer', 'Chief Operating Officer (COO)', 'Administrative Staff', 'Governance & Executive Leadership', 'admin', 'Standardized EMR role template', 5, TRUE),
  ('governance-executive-leadership-chief-medical-officer', 'Chief Medical Officer (CMO)', 'Clinical Staff', 'Governance & Executive Leadership', 'doctor', 'Standardized EMR role template', 6, TRUE),
  ('governance-executive-leadership-chief-nursing-officer', 'Chief Nursing Officer (CNO)', 'Nursing Staff', 'Governance & Executive Leadership', 'nurse', 'Standardized EMR role template', 7, TRUE),
  ('governance-executive-leadership-chief-financial-officer', 'Chief Financial Officer (CFO)', 'Administrative Staff', 'Governance & Executive Leadership', 'admin', 'Standardized EMR role template', 8, TRUE),
  ('governance-executive-leadership-chief-information-officer', 'Chief Information Officer (CIO)', 'IT & System', 'Governance & Executive Leadership', 'admin', 'Standardized EMR role template', 9, TRUE),
  ('governance-executive-leadership-chief-technology-officer', 'Chief Technology Officer (CTO)', 'IT & System', 'Governance & Executive Leadership', 'admin', 'Standardized EMR role template', 10, TRUE),
  ('governance-executive-leadership-chief-human-resources-officer', 'Chief Human Resources Officer (CHRO)', 'Administrative Staff', 'Governance & Executive Leadership', 'admin', 'Standardized EMR role template', 11, TRUE),
  ('governance-executive-leadership-chief-compliance-officer', 'Chief Compliance Officer', 'Administrative Staff', 'Governance & Executive Leadership', 'admin', 'Standardized EMR role template', 12, TRUE),
  ('medical-staff-medical-director', 'Medical Director', 'Clinical Staff', 'Medical Staff', 'doctor', 'Standardized EMR role template', 13, TRUE),
  ('medical-staff-department-head', 'Department Head (HOD)', 'Clinical Staff', 'Medical Staff', 'doctor', 'Standardized EMR role template', 14, TRUE),
  ('medical-staff-general-practitioner', 'General Practitioner (GP)', 'Clinical Staff', 'Medical Staff', 'doctor', 'Standardized EMR role template', 15, TRUE),
  ('medical-staff-attending-physician', 'Attending Physician', 'Clinical Staff', 'Medical Staff', 'doctor', 'Standardized EMR role template', 16, TRUE),
  ('medical-staff-consultant', 'Consultant (Specialist)', 'Clinical Staff', 'Medical Staff', 'doctor', 'Standardized EMR role template', 17, TRUE),
  ('medical-staff-registrar', 'Registrar', 'Clinical Staff', 'Medical Staff', 'doctor', 'Standardized EMR role template', 18, TRUE),
  ('medical-staff-resident', 'Resident', 'Clinical Staff', 'Medical Staff', 'doctor', 'Standardized EMR role template', 19, TRUE),
  ('medical-staff-intern', 'Intern', 'Clinical Staff', 'Medical Staff', 'doctor', 'Standardized EMR role template', 20, TRUE),
  ('medical-staff-medical-student', 'Medical Student', 'Clinical Staff', 'Medical Staff', 'staff', 'Standardized EMR role template', 21, TRUE),
  ('medical-specialties-cardiologist', 'Cardiologist', 'Clinical Staff', 'Medical Specialties', 'doctor', 'Standardized EMR role template', 22, TRUE),
  ('medical-specialties-neurologist', 'Neurologist', 'Clinical Staff', 'Medical Specialties', 'doctor', 'Standardized EMR role template', 23, TRUE),
  ('medical-specialties-dermatologist', 'Dermatologist', 'Clinical Staff', 'Medical Specialties', 'doctor', 'Standardized EMR role template', 24, TRUE),
  ('medical-specialties-pediatrician', 'Pediatrician', 'Clinical Staff', 'Medical Specialties', 'doctor', 'Standardized EMR role template', 25, TRUE),
  ('medical-specialties-psychiatrist', 'Psychiatrist', 'Clinical Staff', 'Medical Specialties', 'doctor', 'Standardized EMR role template', 26, TRUE),
  ('medical-specialties-oncologist', 'Oncologist', 'Clinical Staff', 'Medical Specialties', 'doctor', 'Standardized EMR role template', 27, TRUE),
  ('medical-specialties-endocrinologist', 'Endocrinologist', 'Clinical Staff', 'Medical Specialties', 'doctor', 'Standardized EMR role template', 28, TRUE),
  ('medical-specialties-gastroenterologist', 'Gastroenterologist', 'Clinical Staff', 'Medical Specialties', 'doctor', 'Standardized EMR role template', 29, TRUE),
  ('medical-specialties-pulmonologist', 'Pulmonologist', 'Clinical Staff', 'Medical Specialties', 'doctor', 'Standardized EMR role template', 30, TRUE),
  ('medical-specialties-nephrologist', 'Nephrologist', 'Clinical Staff', 'Medical Specialties', 'doctor', 'Standardized EMR role template', 31, TRUE),
  ('medical-specialties-infectious-disease-specialist', 'Infectious Disease Specialist', 'Clinical Staff', 'Medical Specialties', 'doctor', 'Standardized EMR role template', 32, TRUE),
  ('medical-specialties-emergency-medicine-physician', 'Emergency Medicine Physician', 'Clinical Staff', 'Medical Specialties', 'doctor', 'Standardized EMR role template', 33, TRUE),
  ('surgical-staff-general-surgeon', 'General Surgeon', 'Clinical Staff', 'Surgical Staff', 'doctor', 'Standardized EMR role template', 34, TRUE),
  ('surgical-staff-orthopedic-surgeon', 'Orthopedic Surgeon', 'Clinical Staff', 'Surgical Staff', 'doctor', 'Standardized EMR role template', 35, TRUE),
  ('surgical-staff-neurosurgeon', 'Neurosurgeon', 'Clinical Staff', 'Surgical Staff', 'doctor', 'Standardized EMR role template', 36, TRUE),
  ('surgical-staff-cardiothoracic-surgeon', 'Cardiothoracic Surgeon', 'Clinical Staff', 'Surgical Staff', 'doctor', 'Standardized EMR role template', 37, TRUE),
  ('surgical-staff-plastic-surgeon', 'Plastic Surgeon', 'Clinical Staff', 'Surgical Staff', 'doctor', 'Standardized EMR role template', 38, TRUE),
  ('surgical-staff-urologist', 'Urologist', 'Clinical Staff', 'Surgical Staff', 'doctor', 'Standardized EMR role template', 39, TRUE),
  ('surgical-staff-obstetrician-gynecologist', 'Obstetrician/Gynecologist (OB/GYN)', 'Clinical Staff', 'Surgical Staff', 'doctor', 'Standardized EMR role template', 40, TRUE),
  ('procedure-based-specialists-anesthesiologist', 'Anesthesiologist', 'Clinical Staff', 'Procedure-Based Specialists', 'doctor', 'Standardized EMR role template', 41, TRUE),
  ('procedure-based-specialists-intensivist', 'Intensivist (ICU)', 'Clinical Staff', 'Procedure-Based Specialists', 'doctor', 'Standardized EMR role template', 42, TRUE),
  ('procedure-based-specialists-radiologist', 'Radiologist', 'Diagnostic Staff', 'Procedure-Based Specialists', 'doctor', 'Standardized EMR role template', 43, TRUE),
  ('procedure-based-specialists-pathologist', 'Pathologist', 'Diagnostic Staff', 'Procedure-Based Specialists', 'doctor', 'Standardized EMR role template', 44, TRUE),
  ('nursing-staff-director-of-nursing', 'Director of Nursing', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 45, TRUE),
  ('nursing-staff-nurse-unit-manager', 'Nurse Unit Manager (Ward Manager)', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 46, TRUE),
  ('nursing-staff-assistant-nurse-manager', 'Assistant Nurse Manager', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 47, TRUE),
  ('nursing-staff-registered-nurse', 'Registered Nurse (RN)', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 48, TRUE),
  ('nursing-staff-enrolled-nurse', 'Enrolled Nurse', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 49, TRUE),
  ('nursing-staff-licensed-practical-nurse', 'Licensed Practical Nurse (LPN)', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 50, TRUE),
  ('nursing-staff-icu-nurse', 'ICU Nurse', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 51, TRUE),
  ('nursing-staff-emergency-triage-nurse', 'Emergency/Triage Nurse', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 52, TRUE),
  ('nursing-staff-surgical-nurse', 'Surgical Nurse', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 53, TRUE),
  ('nursing-staff-pediatric-nurse', 'Pediatric Nurse', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 54, TRUE),
  ('nursing-staff-oncology-nurse', 'Oncology Nurse', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 55, TRUE),
  ('nursing-staff-dialysis-nurse', 'Dialysis Nurse', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 56, TRUE),
  ('nursing-staff-infection-control-nurse', 'Infection Control Nurse', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 57, TRUE),
  ('nursing-staff-psychiatric-nurse', 'Psychiatric Nurse', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 58, TRUE),
  ('nursing-staff-community-health-nurse', 'Community Health Nurse', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 59, TRUE),
  ('nursing-staff-midwife', 'Midwife', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 60, TRUE),
  ('nursing-staff-nurse-practitioner', 'Nurse Practitioner (NP)', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 61, TRUE),
  ('nursing-staff-clinical-nurse-specialist', 'Clinical Nurse Specialist', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 62, TRUE),
  ('nursing-staff-nurse-educator', 'Nurse Educator', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 63, TRUE),
  ('nursing-staff-nurse-researcher', 'Nurse Researcher', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 64, TRUE),
  ('nursing-staff-ward-nurse', 'Ward Nurse', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 65, TRUE),
  ('nursing-staff-charge-nurse', 'Charge Nurse', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 66, TRUE),
  ('nursing-staff-bedside-nurse', 'Bedside Nurse', 'Nursing Staff', 'Nursing Staff', 'nurse', 'Standardized EMR role template', 67, TRUE),
  ('nursing-staff-nurse-assistant-nursing-aide', 'Nurse Assistant / Nursing Aide', 'Nursing Staff', 'Nursing Staff', 'staff', 'Standardized EMR role template', 68, TRUE),
  ('allied-health-professionals-physiotherapist', 'Physiotherapist', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 69, TRUE),
  ('allied-health-professionals-occupational-therapist', 'Occupational Therapist', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 70, TRUE),
  ('allied-health-professionals-speech-language-therapist', 'Speech & Language Therapist', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 71, TRUE),
  ('allied-health-professionals-respiratory-therapist', 'Respiratory Therapist', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 72, TRUE),
  ('allied-health-professionals-dietitian', 'Dietitian', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 73, TRUE),
  ('allied-health-professionals-nutritionist', 'Nutritionist', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 74, TRUE),
  ('allied-health-professionals-pharmacist', 'Pharmacist', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 75, TRUE),
  ('allied-health-professionals-clinical-pharmacist', 'Clinical Pharmacist', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 76, TRUE),
  ('allied-health-professionals-pharmacy-technician', 'Pharmacy Technician', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 77, TRUE),
  ('allied-health-professionals-pharmacy-assistant', 'Pharmacy Assistant', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 78, TRUE),
  ('allied-health-professionals-psychologist', 'Psychologist', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 79, TRUE),
  ('allied-health-professionals-social-worker', 'Social Worker', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 80, TRUE),
  ('allied-health-professionals-counselor', 'Counselor', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 81, TRUE),
  ('allied-health-professionals-podiatrist', 'Podiatrist', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 82, TRUE),
  ('allied-health-professionals-audiologist', 'Audiologist', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 83, TRUE),
  ('allied-health-professionals-optometrist', 'Optometrist', 'Allied Health', 'Allied Health Professionals', 'staff', 'Standardized EMR role template', 84, TRUE),
  ('diagnostic-laboratory-staff-laboratory-director', 'Laboratory Director', 'Diagnostic Staff', 'Diagnostic & Laboratory Staff', 'staff', 'Standardized EMR role template', 85, TRUE),
  ('diagnostic-laboratory-staff-medical-laboratory-scientist', 'Medical Laboratory Scientist', 'Diagnostic Staff', 'Diagnostic & Laboratory Staff', 'staff', 'Standardized EMR role template', 86, TRUE),
  ('diagnostic-laboratory-staff-lab-technician', 'Lab Technician', 'Diagnostic Staff', 'Diagnostic & Laboratory Staff', 'staff', 'Standardized EMR role template', 87, TRUE),
  ('diagnostic-laboratory-staff-phlebotomist', 'Phlebotomist', 'Diagnostic Staff', 'Diagnostic & Laboratory Staff', 'staff', 'Standardized EMR role template', 88, TRUE),
  ('diagnostic-laboratory-staff-radiographer', 'Radiographer', 'Diagnostic Staff', 'Diagnostic & Laboratory Staff', 'staff', 'Standardized EMR role template', 89, TRUE),
  ('diagnostic-laboratory-staff-sonographer', 'Sonographer (Ultrasound)', 'Diagnostic Staff', 'Diagnostic & Laboratory Staff', 'staff', 'Standardized EMR role template', 90, TRUE),
  ('diagnostic-laboratory-staff-ct-mri-technician', 'CT/MRI Technician', 'Diagnostic Staff', 'Diagnostic & Laboratory Staff', 'staff', 'Standardized EMR role template', 91, TRUE),
  ('diagnostic-laboratory-staff-biomedical-engineer', 'Biomedical Engineer', 'Diagnostic Staff', 'Diagnostic & Laboratory Staff', 'staff', 'Standardized EMR role template', 92, TRUE),
  ('diagnostic-laboratory-staff-medical-equipment-technician', 'Medical Equipment Technician', 'Diagnostic Staff', 'Diagnostic & Laboratory Staff', 'staff', 'Standardized EMR role template', 93, TRUE),
  ('emergency-critical-care-emergency-physician', 'Emergency Physician', 'Clinical Staff', 'Emergency & Critical Care', 'doctor', 'Standardized EMR role template', 94, TRUE),
  ('emergency-critical-care-trauma-team-member', 'Trauma Team Member', 'Clinical Staff', 'Emergency & Critical Care', 'staff', 'Standardized EMR role template', 95, TRUE),
  ('emergency-critical-care-paramedic', 'Paramedic', 'Clinical Staff', 'Emergency & Critical Care', 'staff', 'Standardized EMR role template', 96, TRUE),
  ('emergency-critical-care-emergency-nurse', 'Emergency Nurse', 'Nursing Staff', 'Emergency & Critical Care', 'nurse', 'Standardized EMR role template', 97, TRUE),
  ('emergency-critical-care-icu-staff', 'ICU Staff', 'Nursing Staff', 'Emergency & Critical Care', 'nurse', 'Standardized EMR role template', 98, TRUE),
  ('emergency-critical-care-ambulance-driver', 'Ambulance Driver', 'Support Staff', 'Emergency & Critical Care', 'staff', 'Standardized EMR role template', 99, TRUE),
  ('emergency-critical-care-first-responder', 'First Responder', 'Support Staff', 'Emergency & Critical Care', 'staff', 'Standardized EMR role template', 100, TRUE),
  ('inpatient-ward-support-ward-clerk', 'Ward Clerk', 'Support Staff', 'Inpatient / Ward Support', 'staff', 'Standardized EMR role template', 101, TRUE),
  ('inpatient-ward-support-patient-care-assistant', 'Patient Care Assistant', 'Support Staff', 'Inpatient / Ward Support', 'staff', 'Standardized EMR role template', 102, TRUE),
  ('inpatient-ward-support-healthcare-assistant', 'Healthcare Assistant', 'Support Staff', 'Inpatient / Ward Support', 'staff', 'Standardized EMR role template', 103, TRUE),
  ('inpatient-ward-support-porter', 'Porter (Patient Transport)', 'Support Staff', 'Inpatient / Ward Support', 'staff', 'Standardized EMR role template', 104, TRUE),
  ('inpatient-ward-support-bed-manager', 'Bed Manager', 'Administrative Staff', 'Inpatient / Ward Support', 'admin', 'Standardized EMR role template', 105, TRUE),
  ('inpatient-ward-support-admission-discharge-coordinator', 'Admission/Discharge Coordinator', 'Administrative Staff', 'Inpatient / Ward Support', 'admin', 'Standardized EMR role template', 106, TRUE),
  ('administration-management-hospital-administrator', 'Hospital Administrator', 'Administrative Staff', 'Administration & Management', 'admin', 'Standardized EMR role template', 107, TRUE),
  ('administration-management-operations-manager', 'Operations Manager', 'Administrative Staff', 'Administration & Management', 'admin', 'Standardized EMR role template', 108, TRUE),
  ('administration-management-department-coordinator', 'Department Coordinator', 'Administrative Staff', 'Administration & Management', 'admin', 'Standardized EMR role template', 109, TRUE),
  ('administration-management-health-information-manager', 'Health Information Manager', 'Administrative Staff', 'Administration & Management', 'admin', 'Standardized EMR role template', 110, TRUE),
  ('administration-management-medical-records-officer', 'Medical Records Officer', 'Administrative Staff', 'Administration & Management', 'staff', 'Standardized EMR role template', 111, TRUE),
  ('administration-management-medical-coder', 'Medical Coder', 'Administrative Staff', 'Administration & Management', 'staff', 'Standardized EMR role template', 112, TRUE),
  ('administration-management-medical-biller', 'Medical Biller', 'Administrative Staff', 'Administration & Management', 'staff', 'Standardized EMR role template', 113, TRUE),
  ('administration-management-accountant', 'Accountant', 'Administrative Staff', 'Administration & Management', 'staff', 'Standardized EMR role template', 114, TRUE),
  ('administration-management-billing-officer', 'Billing Officer', 'Administrative Staff', 'Administration & Management', 'staff', 'Standardized EMR role template', 115, TRUE),
  ('administration-management-insurance-coordinator', 'Insurance Coordinator', 'Administrative Staff', 'Administration & Management', 'staff', 'Standardized EMR role template', 116, TRUE),
  ('administration-management-hr-manager', 'HR Manager', 'Administrative Staff', 'Administration & Management', 'admin', 'Standardized EMR role template', 117, TRUE),
  ('administration-management-recruiter', 'Recruiter', 'Administrative Staff', 'Administration & Management', 'staff', 'Standardized EMR role template', 118, TRUE),
  ('administration-management-training-coordinator', 'Training Coordinator', 'Administrative Staff', 'Administration & Management', 'staff', 'Standardized EMR role template', 119, TRUE),
  ('it-digital-health-health-it-specialist', 'Health IT Specialist', 'IT & System', 'IT & Digital Health', 'staff', 'Standardized EMR role template', 120, TRUE),
  ('it-digital-health-emr-ehr-administrator', 'EMR/EHR Administrator', 'IT & System', 'IT & Digital Health', 'admin', 'Standardized EMR role template', 121, TRUE),
  ('it-digital-health-system-administrator', 'System Administrator', 'IT & System', 'IT & Digital Health', 'admin', 'Standardized EMR role template', 122, TRUE),
  ('it-digital-health-database-administrator', 'Database Administrator', 'IT & System', 'IT & Digital Health', 'admin', 'Standardized EMR role template', 123, TRUE),
  ('it-digital-health-cybersecurity-specialist', 'Cybersecurity Specialist', 'IT & System', 'IT & Digital Health', 'staff', 'Standardized EMR role template', 124, TRUE),
  ('it-digital-health-data-analyst', 'Data Analyst (Healthcare)', 'IT & System', 'IT & Digital Health', 'staff', 'Standardized EMR role template', 125, TRUE),
  ('it-digital-health-ai-clinical-decision-support-engineer', 'AI/Clinical Decision Support Engineer', 'IT & System', 'IT & Digital Health', 'staff', 'Standardized EMR role template', 126, TRUE),
  ('support-facility-cleaner-housekeeping-staff', 'Cleaner / Housekeeping Staff', 'Support Staff', 'Support & Facility', 'staff', 'Standardized EMR role template', 127, TRUE),
  ('support-facility-infection-control-staff', 'Infection Control Staff', 'Support Staff', 'Support & Facility', 'staff', 'Standardized EMR role template', 128, TRUE),
  ('support-facility-waste-management-staff', 'Waste Management Staff', 'Support Staff', 'Support & Facility', 'staff', 'Standardized EMR role template', 129, TRUE),
  ('support-facility-kitchen-staff', 'Kitchen Staff', 'Support Staff', 'Support & Facility', 'staff', 'Standardized EMR role template', 130, TRUE),
  ('support-facility-diet-kitchen-assistant', 'Diet Kitchen Assistant', 'Support Staff', 'Support & Facility', 'staff', 'Standardized EMR role template', 131, TRUE),
  ('support-facility-food-service-worker', 'Food Service Worker', 'Support Staff', 'Support & Facility', 'staff', 'Standardized EMR role template', 132, TRUE),
  ('support-facility-security-guard', 'Security Guard', 'Support Staff', 'Support & Facility', 'staff', 'Standardized EMR role template', 133, TRUE),
  ('support-facility-safety-officer', 'Safety Officer', 'Support Staff', 'Support & Facility', 'staff', 'Standardized EMR role template', 134, TRUE),
  ('support-facility-store-manager', 'Store Manager', 'Support Staff', 'Support & Facility', 'staff', 'Standardized EMR role template', 135, TRUE),
  ('support-facility-inventory-manager', 'Inventory Manager', 'Support Staff', 'Support & Facility', 'staff', 'Standardized EMR role template', 136, TRUE),
  ('support-facility-supply-chain-officer', 'Supply Chain Officer', 'Support Staff', 'Support & Facility', 'staff', 'Standardized EMR role template', 137, TRUE),
  ('pharmacy-medication-management-chief-pharmacist', 'Chief Pharmacist', 'Allied Health', 'Pharmacy & Medication Management', 'staff', 'Standardized EMR role template', 138, TRUE),
  ('pharmacy-medication-management-dispensing-pharmacist', 'Dispensing Pharmacist', 'Allied Health', 'Pharmacy & Medication Management', 'staff', 'Standardized EMR role template', 139, TRUE),
  ('pharmacy-medication-management-inventory-pharmacist', 'Inventory Pharmacist', 'Allied Health', 'Pharmacy & Medication Management', 'staff', 'Standardized EMR role template', 140, TRUE),
  ('community-outreach-community-health-worker', 'Community Health Worker', 'External / Community', 'Community & Outreach', 'staff', 'Standardized EMR role template', 141, TRUE),
  ('community-outreach-health-extension-worker', 'Health Extension Worker', 'External / Community', 'Community & Outreach', 'staff', 'Standardized EMR role template', 142, TRUE),
  ('community-outreach-outreach-coordinator', 'Outreach Coordinator', 'External / Community', 'Community & Outreach', 'staff', 'Standardized EMR role template', 143, TRUE),
  ('community-outreach-public-health-officer', 'Public Health Officer', 'External / Community', 'Community & Outreach', 'staff', 'Standardized EMR role template', 144, TRUE),
  ('community-outreach-epidemiologist', 'Epidemiologist', 'External / Community', 'Community & Outreach', 'staff', 'Standardized EMR role template', 145, TRUE),
  ('education-research-medical-educator', 'Medical Educator', 'Clinical Staff', 'Education & Research', 'doctor', 'Standardized EMR role template', 146, TRUE),
  ('education-research-clinical-trainer', 'Clinical Trainer', 'Clinical Staff', 'Education & Research', 'staff', 'Standardized EMR role template', 147, TRUE),
  ('education-research-research-scientist', 'Research Scientist', 'Clinical Staff', 'Education & Research', 'staff', 'Standardized EMR role template', 148, TRUE),
  ('education-research-clinical-trial-coordinator', 'Clinical Trial Coordinator', 'Clinical Staff', 'Education & Research', 'staff', 'Standardized EMR role template', 149, TRUE),
  ('education-research-academic-staff', 'Academic Staff', 'Clinical Staff', 'Education & Research', 'staff', 'Standardized EMR role template', 150, TRUE),
  ('legal-compliance-legal-advisor', 'Legal Advisor', 'Administrative Staff', 'Legal & Compliance', 'admin', 'Standardized EMR role template', 151, TRUE),
  ('legal-compliance-compliance-officer', 'Compliance Officer', 'Administrative Staff', 'Legal & Compliance', 'admin', 'Standardized EMR role template', 152, TRUE),
  ('legal-compliance-risk-manager', 'Risk Manager', 'Administrative Staff', 'Legal & Compliance', 'admin', 'Standardized EMR role template', 153, TRUE),
  ('legal-compliance-ethics-committee-member', 'Ethics Committee Member', 'Administrative Staff', 'Legal & Compliance', 'admin', 'Standardized EMR role template', 154, TRUE)
ON CONFLICT (template_key) DO UPDATE
SET
  title = EXCLUDED.title,
  role_group = EXCLUDED.role_group,
  category = EXCLUDED.category,
  api_role = EXCLUDED.api_role,
  description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order,
  active = TRUE,
  updated_at = NOW();

-- Deactivate legacy keys from pre-canonical seed that differ only by abbreviation suffixes.
UPDATE staff_role_templates
SET
  active = FALSE,
  updated_at = NOW()
WHERE template_key IN (
  'medical-staff-department-head-hod',
  'medical-staff-general-practitioner-gp',
  'medical-staff-consultant-specialist',
  'surgical-staff-obstetrician-gynecologist-ob-gyn',
  'procedure-based-specialists-intensivist-icu',
  'nursing-staff-nurse-unit-manager-ward-manager',
  'nursing-staff-registered-nurse-rn',
  'nursing-staff-licensed-practical-nurse-lpn',
  'nursing-staff-nurse-practitioner-np'
);