-- 022_seed_tier_based_staff_assignments.sql
-- Seed demo staff assignments aligned with organization tiers and real-world standards.

-- Remove old copy migration file (housekeeping)
DELETE FROM organization_staff_template_requests WHERE id IS NOT NULL;

-- Health Post tier demo staff (hp-clinic-01)
INSERT INTO organization_staff_template_requests (organization_id, staff_template_key, requested_by, status, justification, approved_by, approved_at)
SELECT
  org.id,
  template,
  (SELECT id FROM users WHERE email = 'admin.hp01@tenadam.local'),
  'approved',
  'Essential staff for Health Post operations.',
  (SELECT id FROM users WHERE email = 'superadmin@tenadam.local'),
  NOW()
FROM organizations org
CROSS JOIN (VALUES
  ('med-gp'),
  ('nurse-rn'),
  ('nurse-lpn'),
  ('allied-pharmacist'),
  ('diag-lab-tech'),
  ('nurse-aide'),
  ('admin-hospital'),
  ('admin-training'),
  ('support-security'),
  ('support-housekeeping'),
  ('comm-health-worker')
) AS t(template)
WHERE org.slug = 'hp-clinic-01'
ON CONFLICT (organization_id, staff_template_key) DO UPDATE SET
  status = 'approved',
  approved_at = NOW(),
  updated_at = NOW();

-- Health Center tier demo staff (hc-center-01)
INSERT INTO organization_staff_template_requests (organization_id, staff_template_key, requested_by, status, justification, approved_by, approved_at)
SELECT
  org.id,
  template,
  (SELECT id FROM users WHERE email = 'admin.hc01@tenadam.local'),
  'approved',
  'Extended services for Health Center with OPD, emergency, and lab.',
  (SELECT id FROM users WHERE email = 'superadmin@tenadam.local'),
  NOW()
FROM organizations org
CROSS JOIN (VALUES
  ('med-gp'),
  ('med-director'),
  ('med-intern'),
  ('nurse-rn'),
  ('nurse-enrolled'),
  ('nurse-manager'),
  ('nurse-triage'),
  ('nurse-charge'),
  ('nurse-comm'),
  ('nurse-midwife'),
  ('nurse-aide'),
  ('allied-pharmacist'),
  ('allied-pharm-tech'),
  ('allied-dietitian'),
  ('allied-social-worker'),
  ('diag-lab-director'),
  ('diag-lab-tech'),
  ('diag-sonographer'),
  ('er-paramedic'),
  ('ward-clerk'),
  ('ward-healthcare-asst'),
  ('admin-hospital'),
  ('admin-ops-manager'),
  ('admin-billing-off'),
  ('admin-recruiter'),
  ('admin-records-off'),
  ('admin-training'),
  ('it-health-spec'),
  ('support-housekeeping'),
  ('support-security'),
  ('support-waste'),
  ('support-food-worker'),
  ('support-inventory'),
  ('comm-health-worker'),
  ('comm-outreach-coord'),
  ('legal-compliance')
) AS t(template)
WHERE org.slug = 'hc-center-01'
ON CONFLICT (organization_id, staff_template_key) DO UPDATE SET
  status = 'approved',
  approved_at = NOW(),
  updated_at = NOW();

-- Primary Hospital tier demo staff (ph-hospital-01)
INSERT INTO organization_staff_template_requests (organization_id, staff_template_key, requested_by, status, justification, approved_by, approved_at)
SELECT
  org.id,
  template,
  (SELECT id FROM users WHERE email = 'admin.ph01@tenadam.local'),
  'approved',
  'Comprehensive staffing for Primary Hospital with surgical and inpatient capabilities.',
  (SELECT id FROM users WHERE email = 'superadmin@tenadam.local'),
  NOW()
FROM organizations org
CROSS JOIN (VALUES
  ('gov-cmo'),
  ('gov-cno'),
  ('gov-coo'),
  ('med-director'),
  ('med-hod'),
  ('med-attending'),
  ('med-gp'),
  ('med-registrar'),
  ('med-resident'),
  ('med-intern'),
  ('spec-pediatrician'),
  ('spec-dermatologist'),
  ('spec-gastro'),
  ('spec-pulmonologist'),
  ('spec-infectious'),
  ('spec-er-physician'),
  ('surg-general'),
  ('surg-urologist'),
  ('surg-obgyn'),
  ('proc-anesthesiologist'),
  ('proc-intensivist'),
  ('proc-radiologist'),
  ('nurse-director'),
  ('nurse-manager'),
  ('nurse-asst-manager'),
  ('nurse-rn'),
  ('nurse-enrolled'),
  ('nurse-lpn'),
  ('nurse-icu'),
  ('nurse-triage'),
  ('nurse-surgical'),
  ('nurse-peds'),
  ('nurse-midwife'),
  ('nurse-clinical-spec'),
  ('nurse-educator'),
  ('nurse-ward'),
  ('nurse-charge'),
  ('nurse-bedside'),
  ('nurse-aide'),
  ('allied-pharmacist'),
  ('allied-clin-pharm'),
  ('allied-pharm-tech'),
  ('allied-pharm-asst'),
  ('allied-physio'),
  ('allied-occupational'),
  ('allied-dietitian'),
  ('allied-nutritionist'),
  ('allied-social-worker'),
  ('allied-psychologist'),
  ('diag-lab-director'),
  ('diag-lab-scientist'),
  ('diag-lab-tech'),
  ('diag-phleb'),
  ('diag-radiographer'),
  ('diag-sonographer'),
  ('diag-equip-tech'),
  ('er-physician'),
  ('er-nurse'),
  ('er-icu-staff'),
  ('er-ambulance'),
  ('er-first-responder'),
  ('ward-clerk'),
  ('ward-patient-asst'),
  ('ward-healthcare-asst'),
  ('ward-porter'),
  ('ward-admission-coord'),
  ('admin-hospital'),
  ('admin-ops-manager'),
  ('admin-dept-coord'),
  ('admin-health-info'),
  ('admin-records-off'),
  ('admin-billing-off'),
  ('admin-insurance'),
  ('admin-coder'),
  ('admin-training'),
  ('admin-recruiter'),
  ('admin-hr-manager'),
  ('it-health-spec'),
  ('it-emr-admin'),
  ('it-sys-admin'),
  ('it-db-admin'),
  ('it-data-analyst'),
  ('support-housekeeping'),
  ('support-infection'),
  ('support-waste'),
  ('support-kitchen'),
  ('support-diet-asst'),
  ('support-food-worker'),
  ('support-security'),
  ('support-safety'),
  ('support-inventory'),
  ('support-supply'),
  ('support-store-mgr'),
  ('pharm-chief'),
  ('pharm-dispensing'),
  ('pharm-inventory'),
  ('comm-health-worker'),
  ('comm-outreach-coord'),
  ('edu-medical'),
  ('edu-clin-trainer'),
  ('legal-advisor'),
  ('legal-compliance'),
  ('legal-risk-mgr')
) AS t(template)
WHERE org.slug = 'ph-hospital-01'
ON CONFLICT (organization_id, staff_template_key) DO UPDATE SET
  status = 'approved',
  approved_at = NOW(),
  updated_at = NOW();

-- General Specialized Hospital tier (gs-hospital-01)
INSERT INTO organization_staff_template_requests (organization_id, staff_template_key, requested_by, status, justification, approved_by, approved_at)
SELECT
  org.id,
  template,
  (SELECT id FROM users WHERE email = 'admin.gs01@tenadam.local'),
  'approved',
  'Advanced specialized hospital with multiple departments and specialist coverage.',
  (SELECT id FROM users WHERE email = 'superadmin@tenadam.local'),
  NOW()
FROM organizations org
CROSS JOIN (VALUES
  ('gov-board-directors'),
  ('gov-ceo'),
  ('gov-coo'),
  ('gov-cmo'),
  ('gov-cno'),
  ('gov-cfo'),
  ('gov-chro'),
  ('med-director'),
  ('med-hod'),
  ('med-attending'),
  ('med-consultant'),
  ('med-registrar'),
  ('med-resident'),
  ('spec-cardiologist'),
  ('spec-neurologist'),
  ('spec-psychiatrist'),
  ('spec-oncologist'),
  ('spec-endocrinologist'),
  ('spec-nephrologist'),
  ('surg-general'),
  ('surg-ortho'),
  ('surg-neuro'),
  ('surg-plastic'),
  ('surg-urologist'),
  ('surg-obgyn'),
  ('proc-anesthesiologist'),
  ('proc-intensivist'),
  ('proc-radiologist'),
  ('proc-pathologist'),
  ('nurse-director'),
  ('nurse-manager'),
  ('nurse-asst-manager'),
  ('nurse-rn'),
  ('nurse-icu'),
  ('nurse-triage'),
  ('nurse-surgical'),
  ('nurse-peds'),
  ('nurse-oncology'),
  ('nurse-dialysis'),
  ('nurse-psych'),
  ('nurse-midwife'),
  ('nurse-np'),
  ('nurse-clinical-spec'),
  ('nurse-educator'),
  ('nurse-researcher'),
  ('allied-pharmacist'),
  ('allied-clin-pharm'),
  ('allied-psychologist'),
  ('allied-speech'),
  ('allied-respiratory'),
  ('diag-lab-director'),
  ('diag-lab-scientist'),
  ('diag-radiographer'),
  ('diag-sonographer'),
  ('diag-imaging-tech'),
  ('diag-biomed-eng'),
  ('admin-hospital'),
  ('admin-ops-manager'),
  ('admin-health-info'),
  ('admin-hr-manager'),
  ('it-health-spec'),
  ('it-emr-admin'),
  ('it-sys-admin'),
  ('it-cyber-spec'),
  ('it-data-analyst'),
  ('pharm-chief'),
  ('comm-public-health'),
  ('comm-epidemiologist'),
  ('edu-medical'),
  ('res-scientist'),
  ('res-trial-coord'),
  ('legal-advisor'),
  ('legal-compliance'),
  ('legal-risk-mgr'),
  ('legal-ethics-comm')
) AS t(template)
WHERE org.slug = 'gs-hospital-01'
ON CONFLICT (organization_id, staff_template_key) DO UPDATE SET
  status = 'approved',
  approved_at = NOW(),
  updated_at = NOW();

-- National Health System tier (nh-system-01)
INSERT INTO organization_staff_template_requests (organization_id, staff_template_key, requested_by, status, justification, approved_by, approved_at)
SELECT
  org.id,
  template,
  (SELECT id FROM users WHERE email = 'admin.nh01@tenadam.local'),
  'approved',
  'National Health System node with full capability for complex cases and research.',
  (SELECT id FROM users WHERE email = 'superadmin@tenadam.local'),
  NOW()
FROM organizations org
CROSS JOIN (VALUES
  ('gov-board-directors'),
  ('gov-trustees'),
  ('gov-ceo'),
  ('gov-coo'),
  ('gov-cmo'),
  ('gov-cno'),
  ('gov-cfo'),
  ('gov-cio'),
  ('gov-cto'),
  ('gov-chro'),
  ('gov-compliance-chief'),
  ('med-director'),
  ('med-hod'),
  ('med-attending'),
  ('med-consultant'),
  ('med-registrar'),
  ('med-resident'),
  ('med-student'),
  ('spec-cardiologist'),
  ('spec-neurologist'),
  ('spec-psychiatrist'),
  ('spec-oncologist'),
  ('spec-endocrinologist'),
  ('spec-nephrologist'),
  ('surg-general'),
  ('surg-ortho'),
  ('surg-neuro'),
  ('surg-cardio'),
  ('surg-plastic'),
  ('surg-urologist'),
  ('surg-obgyn'),
  ('proc-anesthesiologist'),
  ('proc-intensivist'),
  ('proc-radiologist'),
  ('proc-pathologist'),
  ('nurse-director'),
  ('nurse-manager'),
  ('nurse-asst-manager'),
  ('nurse-rn'),
  ('nurse-icu'),
  ('nurse-surgical'),
  ('nurse-peds'),
  ('nurse-oncology'),
  ('nurse-dialysis'),
  ('nurse-psych'),
  ('nurse-midwife'),
  ('nurse-np'),
  ('nurse-clinical-spec'),
  ('nurse-educator'),
  ('nurse-researcher'),
  ('allied-pharmacist'),
  ('allied-clin-pharm'),
  ('allied-psychologist'),
  ('allied-speech'),
  ('allied-respiratory'),
  ('diag-lab-director'),
  ('diag-lab-scientist'),
  ('diag-radiographer'),
  ('diag-sonographer'),
  ('diag-imaging-tech'),
  ('diag-biomed-eng'),
  ('admin-hospital'),
  ('admin-ops-manager'),
  ('admin-health-info'),
  ('admin-hr-manager'),
  ('it-health-spec'),
  ('it-emr-admin'),
  ('it-sys-admin'),
  ('it-cyber-spec'),
  ('it-data-analyst'),
  ('it-ai-engineer'),
  ('pharm-chief'),
  ('comm-public-health'),
  ('comm-epidemiologist'),
  ('edu-medical'),
  ('res-scientist'),
  ('res-trial-coord'),
  ('res-academic'),
  ('legal-advisor'),
  ('legal-compliance'),
  ('legal-risk-mgr'),
  ('legal-ethics-comm')
) AS t(template)
WHERE org.slug = 'nh-system-01'
ON CONFLICT (organization_id, staff_template_key) DO UPDATE SET
  status = 'approved',
  approved_at = NOW(),
  updated_at = NOW();
