-- Staff Roles and Templates Migration
-- Comprehensive healthcare roles and staff template system

-- 1. Create/update roles table with all valid system roles
INSERT INTO roles (id, name, description, active, created_at, updated_at) VALUES
-- Executive/Governance Roles
('admin-exec-id', 'admin_exec', 'Executive Administrator', TRUE, NOW(), NOW()),
-- Doctor Roles
('doctor-id', 'doctor', 'Doctor/Physician', TRUE, NOW(), NOW()),
('doctor-exec-id', 'doctor_exec', 'Doctor Executive (CMO, Medical Director)', TRUE, NOW(), NOW()),
('doctor-gp-id', 'doctor_gp', 'General Practitioner', TRUE, NOW(), NOW()),
('doctor-specialist-id', 'doctor_specialist', 'Specialist/Consultant', TRUE, NOW(), NOW()),
('doctor-surgeon-id', 'doctor_surgeon', 'Surgeon', TRUE, NOW(), NOW()),
('doctor-anes-id', 'doctor_anes', 'Anesthesiologist', TRUE, NOW(), NOW()),
('doctor-icu-id', 'doctor_icu', 'Intensivist (ICU)', TRUE, NOW(), NOW()),
('doctor-radio-id', 'doctor_radio', 'Radiologist', TRUE, NOW(), NOW()),
('doctor-path-id', 'doctor_path', 'Pathologist', TRUE, NOW(), NOW()),
('doctor-er-id', 'doctor_er', 'Emergency Medicine Physician', TRUE, NOW(), NOW()),
('doctor-psych-id', 'doctor_psych', 'Psychiatrist', TRUE, NOW(), NOW()),
('doctor-intern-id', 'doctor_intern', 'Medical Intern', TRUE, NOW(), NOW()),
('doctor-resident-id', 'doctor_resident', 'Medical Resident', TRUE, NOW(), NOW()),
('doctor-registrar-id', 'doctor_registrar', 'Medical Registrar', TRUE, NOW(), NOW()),
('doctor-senior-id', 'doctor_senior', 'Attending Physician', TRUE, NOW(), NOW()),
('doctor-lead-id', 'doctor_lead', 'Department Head (HOD)', TRUE, NOW(), NOW()),
('doctor-edu-id', 'doctor_edu', 'Medical Educator', TRUE, NOW(), NOW()),
('doctor-student-id', 'doctor_student', 'Medical Student', TRUE, NOW(), NOW()),
-- Nurse Roles
('nurse-id', 'nurse', 'Nurse', TRUE, NOW(), NOW()),
('nurse-exec-id', 'nurse_exec', 'Nurse Executive (CNO, Director)', TRUE, NOW(), NOW()),
('nurse-lead-id', 'nurse_lead', 'Nurse Leader (Manager, Charge Nurse)', TRUE, NOW(), NOW()),
('nurse-rn-id', 'nurse_rn', 'Registered Nurse (RN)', TRUE, NOW(), NOW()),
('nurse-enrolled-id', 'nurse_enrolled', 'Enrolled Nurse', TRUE, NOW(), NOW()),
('nurse-lpn-id', 'nurse_lpn', 'Licensed Practical Nurse (LPN)', TRUE, NOW(), NOW()),
('nurse-icu-id', 'nurse_icu', 'ICU Nurse', TRUE, NOW(), NOW()),
('nurse-triage-id', 'nurse_triage', 'Emergency/Triage Nurse', TRUE, NOW(), NOW()),
('nurse-surg-id', 'nurse_surg', 'Surgical Nurse', TRUE, NOW(), NOW()),
('nurse-peds-id', 'nurse_peds', 'Pediatric Nurse', TRUE, NOW(), NOW()),
('nurse-onco-id', 'nurse_onco', 'Oncology Nurse', TRUE, NOW(), NOW()),
('nurse-dialysis-id', 'nurse_dialysis', 'Dialysis Nurse', TRUE, NOW(), NOW()),
('nurse-staff-id', 'nurse_staff', 'Infection Control Nurse', TRUE, NOW(), NOW()),
('nurse-psych-id', 'nurse_psych', 'Psychiatric Nurse', TRUE, NOW(), NOW()),
('nurse-comm-id', 'nurse_comm', 'Community Health Nurse', TRUE, NOW(), NOW()),
('nurse-midwife-id', 'nurse_midwife', 'Midwife', TRUE, NOW(), NOW()),
('nurse-np-id', 'nurse_np', 'Nurse Practitioner (NP)', TRUE, NOW(), NOW()),
('nurse-spec-id', 'nurse_spec', 'Clinical Nurse Specialist', TRUE, NOW(), NOW()),
('nurse-edu-id', 'nurse_edu', 'Nurse Educator', TRUE, NOW(), NOW()),
('nurse-research-id', 'nurse_research', 'Nurse Researcher', TRUE, NOW(), NOW()),
('nurse-ward-id', 'nurse_ward', 'Ward Nurse', TRUE, NOW(), NOW()),
('nurse-aide-id', 'nurse_aide', 'Nurse Assistant / Nursing Aide', TRUE, NOW(), NOW()),
-- Lab/Diagnostic Roles
('lab-id', 'lab', 'Laboratory Technician', TRUE, NOW(), NOW()),
('lab-exec-id', 'lab_exec', 'Laboratory Director', TRUE, NOW(), NOW()),
('lab-scientist-id', 'lab_scientist', 'Medical Laboratory Scientist', TRUE, NOW(), NOW()),
('lab-technician-id', 'lab_technician', 'Lab Technician', TRUE, NOW(), NOW()),
('lab-phleb-id', 'lab_phleb', 'Phlebotomist', TRUE, NOW(), NOW()),
-- Pharmacy Roles
('pharm-pharmacist-id', 'pharm_pharmacist', 'Pharmacist', TRUE, NOW(), NOW()),
('pharm-lead-id', 'pharm_lead', 'Chief Pharmacist', TRUE, NOW(), NOW()),
('pharm-tech-id', 'pharm_tech', 'Pharmacy Technician', TRUE, NOW(), NOW()),
('pharm-asst-id', 'pharm_asst', 'Pharmacy Assistant', TRUE, NOW(), NOW()),
-- Allied Health Roles
('allied-physio-id', 'allied_physio', 'Physiotherapist', TRUE, NOW(), NOW()),
('allied-staff-id', 'allied_staff', 'Allied Health Professional', TRUE, NOW(), NOW()),
('allied-diet-id', 'allied_diet', 'Dietitian/Nutritionist', TRUE, NOW(), NOW()),
('allied-psych-id', 'allied_psych', 'Psychologist', TRUE, NOW(), NOW()),
-- Admin Roles
('admin-id', 'admin', 'Administrator', TRUE, NOW(), NOW()),
('admin-exec-id', 'admin_exec', 'Executive Administrator', TRUE, NOW(), NOW()),
('admin-manager-id', 'admin_manager', 'Admin Manager', TRUE, NOW(), NOW()),
('admin-staff-id', 'admin_staff', 'Administrative Staff', TRUE, NOW(), NOW()),
('admin-ward-id', 'admin_ward', 'Ward Administrator', TRUE, NOW(), NOW()),
('admin-records-lead-id', 'admin_records_lead', 'Records Manager', TRUE, NOW(), NOW()),
('admin-records-id', 'admin_records', 'Medical Records Officer', TRUE, NOW(), NOW()),
('admin-billing-id', 'admin_billing', 'Billing Officer', TRUE, NOW(), NOW()),
('admin-finance-id', 'admin_finance', 'Financial Officer', TRUE, NOW(), NOW()),
('admin-hr-id', 'admin_hr', 'HR Manager', TRUE, NOW(), NOW()),
('admin-legal-id', 'admin_legal', 'Legal/Compliance Officer', TRUE, NOW(), NOW()),
-- IT Roles
('it-exec-id', 'it_exec', 'IT Executive (CIO/CTO)', TRUE, NOW(), NOW()),
('it-admin-id', 'it_admin', 'IT Administrator', TRUE, NOW(), NOW()),
('it-staff-id', 'it_staff', 'IT Staff', TRUE, NOW(), NOW()),
('it-security-id', 'it_security', 'Cybersecurity Specialist', TRUE, NOW(), NOW()),
('it-data-id', 'it_data', 'Data Analyst', TRUE, NOW(), NOW()),
('it-ai-eng-id', 'it_ai_eng', 'AI/Clinical Decision Support Engineer', TRUE, NOW(), NOW()),
('it-biomed-id', 'it_biomed', 'Biomedical Engineer', TRUE, NOW(), NOW()),
-- Imaging/Diagnostic Roles
('diag-radiographer-id', 'diag_radiographer', 'Radiographer', TRUE, NOW(), NOW()),
('diag-radio-tech-id', 'diag_radio_tech', 'CT/MRI Technician (Sonographer)', TRUE, NOW(), NOW()),
-- Support Staff Roles
('staff-id', 'staff', 'Support Staff', TRUE, NOW(), NOW()),
('staff-er-id', 'staff_er', 'Emergency Support Staff', TRUE, NOW(), NOW()),
('staff-paramedic-id', 'staff_paramedic', 'Paramedic', TRUE, NOW(), NOW()),
('staff-care-id', 'staff_care', 'Patient Care Assistant', TRUE, NOW(), NOW()),
('staff-logistics-id', 'staff_logistics', 'Logistics/Transport Staff', TRUE, NOW(), NOW()),
('staff-support-id', 'staff_support', 'Support Staff', TRUE, NOW(), NOW()),
('staff-security-id', 'staff_security', 'Security Staff', TRUE, NOW(), NOW()),
('staff-edu-id', 'staff_edu', 'Clinical Trainer', TRUE, NOW(), NOW()),
('staff-research-id', 'staff_research', 'Research Staff', TRUE, NOW(), NOW()),
-- Community Roles
('comm-worker-id', 'comm_worker', 'Community Health Worker', TRUE, NOW(), NOW()),
('comm-extension-id', 'comm_extension', 'Health Extension Worker', TRUE, NOW(), NOW()),
('comm-lead-id', 'comm_lead', 'Public Health/Community Lead', TRUE, NOW(), NOW()),
-- Reception/Front Desk
('reception-id', 'reception', 'Receptionist', TRUE, NOW(), NOW()),
('reception-ward-id', 'reception_ward', 'Ward Receptionist/Clerk', TRUE, NOW(), NOW()),
-- Superadmin
('superadmin-id', 'superadmin', 'Superadmin', TRUE, NOW(), NOW())
ON CONFLICT (name) DO UPDATE SET active = TRUE, updated_at = NOW();

-- 2. Create comprehensive staff role templates with all roles from the provided list
INSERT INTO staff_role_templates (
  id, template_key, title, description, role_group, category, 
  api_role, active, created_at, updated_at
) VALUES

-- GOVERNANCE & EXECUTIVE LEADERSHIP
('tmpl-board-dirs-1', 'governance-board-directors', 'Board of Directors', 'Governance and Executive Leadership', 'Administrative Staff', 'Governance & Executive Leadership', 'admin', TRUE, NOW(), NOW()),
('tmpl-board-dirs-2', 'gov-board-directors', 'Board of Directors - Governance', 'Governance focused', 'Administrative Staff', 'Governance', 'admin_exec', TRUE, NOW(), NOW()),
('tmpl-trustees-1', 'governance-trustees', 'Trustees', 'Governance and Executive Leadership', 'Administrative Staff', 'Governance & Executive Leadership', 'admin', TRUE, NOW(), NOW()),
('tmpl-trustees-2', 'gov-trustees', 'Trustees - Governance', 'Governance focused', 'Administrative Staff', 'Governance', 'admin_exec', TRUE, NOW(), NOW()),
('tmpl-owners-1', 'governance-hospital-owners', 'Hospital Owners', 'Governance and Executive Leadership', 'Administrative Staff', 'Governance & Executive Leadership', 'admin', TRUE, NOW(), NOW()),
('tmpl-owners-2', 'gov-owners', 'Hospital Owners - Governance', 'Governance focused', 'Administrative Staff', 'Governance', 'admin_exec', TRUE, NOW(), NOW()),
('tmpl-ceo-1', 'gov-ceo', 'Chief Executive Officer (CEO)', 'C-Level Executive', 'Administrative Staff', 'Governance', 'admin_exec', TRUE, NOW(), NOW()),
('tmpl-ceo-2', 'governance-ceo', 'CEO - Executive Leadership', 'Governance and Executive Leadership', 'Administrative Staff', 'Governance & Executive Leadership', 'admin', TRUE, NOW(), NOW()),
('tmpl-coo-1', 'gov-coo', 'Chief Operating Officer (COO)', 'C-Level Executive', 'Administrative Staff', 'Governance', 'admin_exec', TRUE, NOW(), NOW()),
('tmpl-coo-2', 'governance-coo', 'COO - Executive Leadership', 'Governance and Executive Leadership', 'Administrative Staff', 'Governance & Executive Leadership', 'admin', TRUE, NOW(), NOW()),
('tmpl-cmo-1', 'gov-cmo', 'Chief Medical Officer (CMO)', 'Clinical Executive', 'Clinical Staff', 'Governance', 'doctor_exec', TRUE, NOW(), NOW()),
('tmpl-cmo-2', 'governance-cmo', 'CMO - Executive Leadership', 'Governance and Executive Leadership', 'Clinical Staff', 'Governance & Executive Leadership', 'doctor', TRUE, NOW(), NOW()),
('tmpl-cno-1', 'gov-cno', 'Chief Nursing Officer (CNO)', 'Nursing Executive', 'Nursing Staff', 'Governance', 'nurse_exec', TRUE, NOW(), NOW()),
('tmpl-cno-2', 'governance-cno', 'CNO - Executive Leadership', 'Governance and Executive Leadership', 'Nursing Staff', 'Governance & Executive Leadership', 'nurse', TRUE, NOW(), NOW()),
('tmpl-cfo-1', 'governance-cfo', 'Chief Financial Officer (CFO)', 'Executive Leadership', 'Administrative Staff', 'Governance & Executive Leadership', 'admin', TRUE, NOW(), NOW()),
('tmpl-cfo-2', 'gov-cfo', 'CFO - Finance', 'Governance', 'Administrative Staff', 'Governance', 'admin_exec', TRUE, NOW(), NOW()),
('tmpl-cio-1', 'governance-cio', 'Chief Information Officer (CIO)', 'Executive Leadership', 'IT & System', 'Governance & Executive Leadership', 'admin', TRUE, NOW(), NOW()),
('tmpl-cio-2', 'gov-cio', 'CIO - IT Executive', 'Governance', 'IT & System', 'Governance', 'it_exec', TRUE, NOW(), NOW()),
('tmpl-cto-1', 'gov-cto', 'Chief Technology Officer (CTO)', 'IT Executive', 'IT & System', 'Governance', 'it_exec', TRUE, NOW(), NOW()),
('tmpl-cto-2', 'governance-cto', 'CTO - Executive Leadership', 'Executive Leadership', 'IT & System', 'Governance & Executive Leadership', 'admin', TRUE, NOW(), NOW()),
('tmpl-chro-1', 'governance-chro', 'Chief Human Resources Officer', 'Executive Leadership', 'Administrative Staff', 'Governance & Executive Leadership', 'admin', TRUE, NOW(), NOW()),
('tmpl-chro-2', 'gov-chro', 'CHRO - HR Executive', 'Governance', 'Administrative Staff', 'Governance', 'admin_exec', TRUE, NOW(), NOW()),
('tmpl-compliance-1', 'governance-compliance', 'Chief Compliance Officer', 'Executive Leadership', 'Administrative Staff', 'Governance & Executive Leadership', 'admin', TRUE, NOW(), NOW()),
('tmpl-compliance-2', 'gov-compliance', 'Compliance Officer - Governance', 'Governance', 'Administrative Staff', 'Governance', 'admin_exec', TRUE, NOW(), NOW()),

-- MEDICAL STAFF
('tmpl-med-director-1', 'medical-director', 'Medical Director', 'Medical Staff', 'Clinical Staff', 'Medical Staff', 'doctor', TRUE, NOW(), NOW()),
('tmpl-med-director-2', 'med-director', 'Medical Director - Executive', 'Medical Staff Executive', 'Clinical Staff', 'Medical Staff', 'doctor_exec', TRUE, NOW(), NOW()),
('tmpl-hod-1', 'medical-hod', 'Department Head (HOD)', 'Medical Staff', 'Clinical Staff', 'Medical Staff', 'doctor', TRUE, NOW(), NOW()),
('tmpl-hod-2', 'med-hod', 'HOD - Department Leadership', 'Medical Staff Leadership', 'Clinical Staff', 'Medical Staff', 'doctor_lead', TRUE, NOW(), NOW()),
('tmpl-gp-1', 'medical-gp', 'General Practitioner (GP)', 'Medical Staff', 'Clinical Staff', 'Medical Staff', 'doctor', TRUE, NOW(), NOW()),
('tmpl-gp-2', 'med-gp', 'General Practitioner - Specialist', 'Medical Staff Specialist', 'Clinical Staff', 'Medical Staff', 'doctor_gp', TRUE, NOW(), NOW()),
('tmpl-attending-1', 'med-attending', 'Attending Physician', 'Senior Medical Staff', 'Clinical Staff', 'Medical Staff', 'doctor_senior', TRUE, NOW(), NOW()),
('tmpl-attending-2', 'medical-attending', 'Attending Physician - Medical Staff', 'Medical Staff', 'Clinical Staff', 'Medical Staff', 'doctor', TRUE, NOW(), NOW()),
('tmpl-consultant-1', 'med-consultant', 'Consultant (Specialist)', 'Specialist Medical Staff', 'Clinical Staff', 'Medical Staff', 'doctor_specialist', TRUE, NOW(), NOW()),
('tmpl-consultant-2', 'medical-consultant', 'Consultant - Medical Staff', 'Medical Staff', 'Clinical Staff', 'Medical Staff', 'doctor', TRUE, NOW(), NOW()),
('tmpl-registrar-1', 'med-registrar', 'Registrar', 'Mid-level Medical Staff', 'Clinical Staff', 'Medical Staff', 'doctor_registrar', TRUE, NOW(), NOW()),
('tmpl-registrar-2', 'medical-registrar', 'Registrar - Medical Staff', 'Medical Staff', 'Clinical Staff', 'Medical Staff', 'doctor', TRUE, NOW(), NOW()),
('tmpl-resident-1', 'med-resident', 'Resident', 'Training Medical Staff', 'Clinical Staff', 'Medical Staff', 'doctor_resident', TRUE, NOW(), NOW()),
('tmpl-resident-2', 'medical-resident', 'Resident - Medical Staff', 'Medical Staff', 'Clinical Staff', 'Medical Staff', 'doctor', TRUE, NOW(), NOW()),
('tmpl-intern-1', 'med-intern', 'Intern', 'Junior Medical Staff', 'Clinical Staff', 'Medical Staff', 'doctor_intern', TRUE, NOW(), NOW()),
('tmpl-intern-2', 'medical-intern', 'Intern - Medical Staff', 'Medical Staff', 'Clinical Staff', 'Medical Staff', 'doctor', TRUE, NOW(), NOW()),
('tmpl-med-student', 'med-student', 'Medical Student', 'Support Staff', 'Clinical Staff', 'Medical Staff', 'doctor_student', TRUE, NOW(), NOW()),
('tmpl-med-student-2', 'medical-med-student', 'Medical Student - Medical Staff', 'Medical Staff', 'Clinical Staff', 'Medical Staff', 'staff', TRUE, NOW(), NOW()),

-- MEDICAL SPECIALTIES
('tmpl-cardio-1', 'spec-cardiologist', 'Cardiologist', 'Medical Specialty', 'Clinical Staff', 'Medical Specialties', 'doctor_specialist', TRUE, NOW(), NOW()),
('tmpl-cardio-2', 'medical-cardiologist', 'Cardiologist - Medical Staff', 'Medical Staff', 'Clinical Staff', 'Medical Specialties', 'doctor', TRUE, NOW(), NOW()),
('tmpl-neuro-1', 'spec-neurologist', 'Neurologist', 'Medical Specialty', 'Clinical Staff', 'Medical Specialties', 'doctor_specialist', TRUE, NOW(), NOW()),
('tmpl-neuro-2', 'medical-neurologist', 'Neurologist - Medical Staff', 'Medical Staff', 'Clinical Staff', 'Medical Specialties', 'doctor', TRUE, NOW(), NOW()),
('tmpl-derm-1', 'spec-dermatologist', 'Dermatologist', 'Medical Specialty', 'Clinical Staff', 'Medical Specialties', 'doctor_specialist', TRUE, NOW(), NOW()),
('tmpl-derm-2', 'medical-dermatologist', 'Dermatologist - Medical Staff', 'Medical Staff', 'Clinical Staff', 'Medical Specialties', 'doctor', TRUE, NOW(), NOW()),
('tmpl-peds-1', 'spec-pediatrician', 'Pediatrician', 'Medical Specialty', 'Clinical Staff', 'Medical Specialties', 'doctor_specialist', TRUE, NOW(), NOW()),
('tmpl-peds-2', 'medical-pediatrician', 'Pediatrician - Medical Staff', 'Medical Staff', 'Clinical Staff', 'Medical Specialties', 'doctor', TRUE, NOW(), NOW()),
('tmpl-psych-1', 'spec-psychiatrist', 'Psychiatrist', 'Medical Specialty', 'Clinical Staff', 'Medical Specialties', 'doctor_psych', TRUE, NOW(), NOW()),
('tmpl-psych-2', 'medical-psychiatrist', 'Psychiatrist - Medical Staff', 'Medical Staff', 'Clinical Staff', 'Medical Specialties', 'doctor', TRUE, NOW(), NOW()),
('tmpl-onco-1', 'spec-oncologist', 'Oncologist', 'Medical Specialty', 'Clinical Staff', 'Medical Specialties', 'doctor_specialist', TRUE, NOW(), NOW()),
('tmpl-onco-2', 'medical-oncologist', 'Oncologist - Medical Staff', 'Medical Staff', 'Clinical Staff', 'Medical Specialties', 'doctor', TRUE, NOW(), NOW()),
('tmpl-endo-1', 'spec-endocrinologist', 'Endocrinologist', 'Medical Specialty', 'Clinical Staff', 'Medical Specialties', 'doctor_specialist', TRUE, NOW(), NOW()),
('tmpl-endo-2', 'medical-endocrinologist', 'Endocrinologist - Medical Staff', 'Medical Staff', 'Clinical Staff', 'Medical Specialties', 'doctor', TRUE, NOW(), NOW()),
('tmpl-gastro-1', 'spec-gastro', 'Gastroenterologist', 'Medical Specialty', 'Clinical Staff', 'Medical Specialties', 'doctor_specialist', TRUE, NOW(), NOW()),
('tmpl-gastro-2', 'medical-gastroenterologist', 'Gastroenterologist - Medical Staff', 'Medical Staff', 'Clinical Staff', 'Medical Specialties', 'doctor', TRUE, NOW(), NOW()),
('tmpl-pulm-1', 'spec-pulmonologist', 'Pulmonologist', 'Medical Specialty', 'Clinical Staff', 'Medical Specialties', 'doctor_specialist', TRUE, NOW(), NOW()),
('tmpl-pulm-2', 'medical-pulmonologist', 'Pulmonologist - Medical Staff', 'Medical Staff', 'Clinical Staff', 'Medical Specialties', 'doctor', TRUE, NOW(), NOW()),
('tmpl-neph-1', 'spec-nephrologist', 'Nephrologist', 'Medical Specialty', 'Clinical Staff', 'Medical Specialties', 'doctor_specialist', TRUE, NOW(), NOW()),
('tmpl-neph-2', 'medical-nephrologist', 'Nephrologist - Medical Staff', 'Medical Staff', 'Clinical Staff', 'Medical Specialties', 'doctor', TRUE, NOW(), NOW()),
('tmpl-infect-1', 'spec-infectious', 'Infectious Disease Specialist', 'Medical Specialty', 'Clinical Staff', 'Medical Specialties', 'doctor_specialist', TRUE, NOW(), NOW()),
('tmpl-infect-2', 'medical-infectious-disease', 'Infectious Disease Specialist - Medical Staff', 'Medical Staff', 'Clinical Staff', 'Medical Specialties', 'doctor', TRUE, NOW(), NOW()),
('tmpl-er-1', 'spec-er-physician', 'Emergency Medicine Physician', 'Medical Specialty', 'Clinical Staff', 'Medical Specialties', 'doctor_er', TRUE, NOW(), NOW()),
('tmpl-er-2', 'medical-emergency-physician', 'Emergency Medicine Physician - Medical Staff', 'Medical Staff', 'Clinical Staff', 'Medical Specialties', 'doctor', TRUE, NOW(), NOW()),

-- SURGICAL STAFF
('tmpl-surg-gen-1', 'surg-general', 'General Surgeon', 'Surgical Staff', 'Clinical Staff', 'Surgical Staff', 'doctor_surgeon', TRUE, NOW(), NOW()),
('tmpl-surg-gen-2', 'medical-general-surgeon', 'General Surgeon - Medical Staff', 'Medical Staff', 'Clinical Staff', 'Surgical Staff', 'doctor', TRUE, NOW(), NOW()),
('tmpl-surg-ortho-1', 'surg-ortho', 'Orthopedic Surgeon', 'Surgical Staff', 'Clinical Staff', 'Surgical Staff', 'doctor_surgeon', TRUE, NOW(), NOW()),
('tmpl-surg-ortho-2', 'medical-orthopedic-surgeon', 'Orthopedic Surgeon - Medical Staff', 'Medical Staff', 'Clinical Staff', 'Surgical Staff', 'doctor', TRUE, NOW(), NOW()),
('tmpl-surg-neuro-1', 'surg-neuro', 'Neurosurgeon', 'Surgical Staff', 'Clinical Staff', 'Surgical Staff', 'doctor_surgeon', TRUE, NOW(), NOW()),
('tmpl-surg-neuro-2', 'medical-neurosurgeon', 'Neurosurgeon - Medical Staff', 'Medical Staff', 'Clinical Staff', 'Surgical Staff', 'doctor', TRUE, NOW(), NOW()),
('tmpl-surg-cardio-1', 'surg-cardio', 'Cardiothoracic Surgeon', 'Surgical Staff', 'Clinical Staff', 'Surgical Staff', 'doctor_surgeon', TRUE, NOW(), NOW()),
('tmpl-surg-cardio-2', 'medical-cardiothoracic-surgeon', 'Cardiothoracic Surgeon - Medical Staff', 'Medical Staff', 'Clinical Staff', 'Surgical Staff', 'doctor', TRUE, NOW(), NOW()),
('tmpl-surg-plastic-1', 'surg-plastic', 'Plastic Surgeon', 'Surgical Staff', 'Clinical Staff', 'Surgical Staff', 'doctor_surgeon', TRUE, NOW(), NOW()),
('tmpl-surg-plastic-2', 'medical-plastic-surgeon', 'Plastic Surgeon - Medical Staff', 'Medical Staff', 'Clinical Staff', 'Surgical Staff', 'doctor', TRUE, NOW(), NOW()),
('tmpl-surg-uro-1', 'surg-urologist', 'Urologist', 'Surgical Staff', 'Clinical Staff', 'Surgical Staff', 'doctor_surgeon', TRUE, NOW(), NOW()),
('tmpl-surg-uro-2', 'medical-urologist', 'Urologist - Medical Staff', 'Medical Staff', 'Clinical Staff', 'Surgical Staff', 'doctor', TRUE, NOW(), NOW()),
('tmpl-surg-obgyn-1', 'surg-obgyn', 'Obstetrician/Gynecologist', 'Surgical Staff', 'Clinical Staff', 'Surgical Staff', 'doctor_surgeon', TRUE, NOW(), NOW()),
('tmpl-surg-obgyn-2', 'medical-obgyn', 'OB/GYN - Medical Staff', 'Medical Staff', 'Clinical Staff', 'Surgical Staff', 'doctor', TRUE, NOW(), NOW()),

-- PROCEDURE-BASED SPECIALISTS
('tmpl-anes-1', 'proc-anesthesiologist', 'Anesthesiologist', 'Procedure-Based Specialist', 'Clinical Staff', 'Procedures', 'doctor_anes', TRUE, NOW(), NOW()),
('tmpl-anes-2', 'medical-anesthesiologist', 'Anesthesiologist - Medical Staff', 'Medical Staff', 'Clinical Staff', 'Procedure-Based Specialists', 'doctor', TRUE, NOW(), NOW()),
('tmpl-icu-1', 'proc-intensivist', 'Intensivist (ICU)', 'Procedure-Based Specialist', 'Clinical Staff', 'Procedures', 'doctor_icu', TRUE, NOW(), NOW()),
('tmpl-icu-2', 'medical-intensivist', 'Intensivist - Medical Staff', 'Medical Staff', 'Clinical Staff', 'Procedure-Based Specialists', 'doctor', TRUE, NOW(), NOW()),
('tmpl-radio-1', 'proc-radiologist', 'Radiologist', 'Diagnostic Staff', 'Diagnostic Staff', 'Procedures', 'doctor_radio', TRUE, NOW(), NOW()),
('tmpl-radio-2', 'medical-radiologist', 'Radiologist - Medical Staff', 'Medical Staff', 'Diagnostic Staff', 'Procedure-Based Specialists', 'doctor', TRUE, NOW(), NOW()),
('tmpl-path-1', 'proc-pathologist', 'Pathologist', 'Diagnostic Staff', 'Diagnostic Staff', 'Procedures', 'doctor_path', TRUE, NOW(), NOW()),
('tmpl-path-2', 'medical-pathologist', 'Pathologist - Medical Staff', 'Medical Staff', 'Diagnostic Staff', 'Procedure-Based Specialists', 'doctor', TRUE, NOW(), NOW()),

-- NURSING STAFF
('tmpl-nurse-dir-1', 'nurse-director', 'Director of Nursing', 'Nursing Executive', 'Nursing Staff', 'Nursing Staff', 'nurse_exec', TRUE, NOW(), NOW()),
('tmpl-nurse-dir-2', 'nursing-director', 'Director of Nursing - Nursing Staff', 'Nursing Staff', 'Nursing Staff', 'Nursing Staff', 'nurse', TRUE, NOW(), NOW()),
('tmpl-nurse-mgr-1', 'nurse-manager', 'Nurse Unit Manager (Ward Manager)', 'Nursing Leadership', 'Nursing Staff', 'Nursing Staff', 'nurse_lead', TRUE, NOW(), NOW()),
('tmpl-nurse-mgr-2', 'nursing-unit-manager', 'Nurse Unit Manager - Nursing Staff', 'Nursing Staff', 'Nursing Staff', 'Nursing Staff', 'nurse', TRUE, NOW(), NOW()),
('tmpl-nurse-asst-mgr-1', 'nurse-asst-manager', 'Assistant Nurse Manager', 'Nursing Leadership', 'Nursing Staff', 'Nursing Staff', 'nurse_lead', TRUE, NOW(), NOW()),
('tmpl-nurse-asst-mgr-2', 'nursing-asst-manager', 'Assistant Nurse Manager - Nursing Staff', 'Nursing Staff', 'Nursing Staff', 'Nursing Staff', 'nurse', TRUE, NOW(), NOW()),
('tmpl-nurse-rn-1', 'nurse-rn', 'Registered Nurse (RN)', 'Nursing Staff', 'Nursing Staff', 'Nursing Staff', 'nurse_rn', TRUE, NOW(), NOW()),
('tmpl-nurse-rn-2', 'nursing-rn', 'Registered Nurse - Nursing Staff', 'Nursing Staff', 'Nursing Staff', 'Nursing Staff', 'nurse', TRUE, NOW(), NOW()),
('tmpl-nurse-enrolled', 'nurse-enrolled', 'Enrolled Nurse', 'Nursing Staff', 'Nursing Staff', 'Nursing Staff', 'nurse_enrolled', TRUE, NOW(), NOW()),
('tmpl-nurse-lpn-1', 'nurse-lpn', 'Licensed Practical Nurse (LPN)', 'Nursing Staff', 'Nursing Staff', 'Nursing Staff', 'nurse_lpn', TRUE, NOW(), NOW()),
('tmpl-nurse-lpn-2', 'nursing-lpn', 'Licensed Practical Nurse - Nursing Staff', 'Nursing Staff', 'Nursing Staff', 'Nursing Staff', 'nurse', TRUE, NOW(), NOW()),
('tmpl-nurse-icu', 'nurse-icu', 'ICU Nurse', 'Specialized Nursing', 'Nursing Staff', 'Nursing Staff', 'nurse_icu', TRUE, NOW(), NOW()),
('tmpl-nurse-triage', 'nurse-triage', 'Emergency/Triage Nurse', 'Specialized Nursing', 'Nursing Staff', 'Nursing Staff', 'nurse_triage', TRUE, NOW(), NOW()),
('tmpl-nurse-surg', 'nurse-surgical', 'Surgical Nurse', 'Specialized Nursing', 'Nursing Staff', 'Nursing Staff', 'nurse_surg', TRUE, NOW(), NOW()),
('tmpl-nurse-peds', 'nurse-peds', 'Pediatric Nurse', 'Specialized Nursing', 'Nursing Staff', 'Nursing Staff', 'nurse_peds', TRUE, NOW(), NOW()),
('tmpl-nurse-onco', 'nurse-oncology', 'Oncology Nurse', 'Specialized Nursing', 'Nursing Staff', 'Nursing Staff', 'nurse_onco', TRUE, NOW(), NOW()),
('tmpl-nurse-dialysis', 'nurse-dialysis', 'Dialysis Nurse', 'Specialized Nursing', 'Nursing Staff', 'Nursing Staff', 'nurse_dialysis', TRUE, NOW(), NOW()),
('tmpl-nurse-infection', 'nurse-infection', 'Infection Control Nurse', 'Specialized Nursing', 'Nursing Staff', 'Nursing Staff', 'nurse_staff', TRUE, NOW(), NOW()),
('tmpl-nurse-psych', 'nurse-psych', 'Psychiatric Nurse', 'Specialized Nursing', 'Nursing Staff', 'Nursing Staff', 'nurse_psych', TRUE, NOW(), NOW()),
('tmpl-nurse-comm', 'nurse-comm', 'Community Health Nurse', 'Specialized Nursing', 'Nursing Staff', 'Nursing Staff', 'nurse_comm', TRUE, NOW(), NOW()),
('tmpl-nurse-midwife', 'nurse-midwife', 'Midwife', 'Specialized Nursing', 'Nursing Staff', 'Nursing Staff', 'nurse_midwife', TRUE, NOW(), NOW()),
('tmpl-nurse-np', 'nurse-np', 'Nurse Practitioner (NP)', 'Specialized Nursing', 'Nursing Staff', 'Nursing Staff', 'nurse_np', TRUE, NOW(), NOW()),
('tmpl-nurse-clin-spec', 'nurse-clinical-spec', 'Clinical Nurse Specialist', 'Specialized Nursing', 'Nursing Staff', 'Nursing Staff', 'nurse_spec', TRUE, NOW(), NOW()),
('tmpl-nurse-educator', 'nurse-educator', 'Nurse Educator', 'Specialized Nursing', 'Nursing Staff', 'Nursing Staff', 'nurse_edu', TRUE, NOW(), NOW()),
('tmpl-nurse-researcher', 'nurse-researcher', 'Nurse Researcher', 'Specialized Nursing', 'Nursing Staff', 'Nursing Staff', 'nurse_research', TRUE, NOW(), NOW()),
('tmpl-nurse-ward', 'nurse-ward', 'Ward Nurse', 'Nursing Staff', 'Nursing Staff', 'Nursing Staff', 'nurse_ward', TRUE, NOW(), NOW()),
('tmpl-nurse-charge', 'nurse-charge', 'Charge Nurse', 'Nursing Leadership', 'Nursing Staff', 'Nursing Staff', 'nurse_lead', TRUE, NOW(), NOW()),
('tmpl-nurse-bedside', 'nurse-bedside', 'Bedside Nurse', 'Nursing Staff', 'Nursing Staff', 'Nursing Staff', 'nurse_ward', TRUE, NOW(), NOW()),
('tmpl-nurse-aide', 'nurse-aide', 'Nurse Assistant / Nursing Aide', 'Support Staff', 'Nursing Staff', 'Nursing Staff', 'nurse_aide', TRUE, NOW(), NOW()),

-- ALLIED HEALTH PROFESSIONALS
('tmpl-allied-physio-1', 'allied-physio', 'Physiotherapist', 'Allied Health', 'Allied Health', 'Allied Health', 'allied_physio', TRUE, NOW(), NOW()),
('tmpl-allied-physio-2', 'allied-health-physio', 'Physiotherapist - Allied Health', 'Allied Health Professional', 'Allied Health', 'Allied Health Professionals', 'staff', TRUE, NOW(), NOW()),
('tmpl-allied-occ-1', 'allied-occupational', 'Occupational Therapist', 'Allied Health', 'Allied Health', 'Allied Health', 'allied_staff', TRUE, NOW(), NOW()),
('tmpl-allied-occ-2', 'allied-health-occ', 'Occupational Therapist - Allied Health', 'Allied Health Professional', 'Allied Health', 'Allied Health Professionals', 'staff', TRUE, NOW(), NOW()),
('tmpl-allied-speech-1', 'allied-speech', 'Speech & Language Therapist', 'Allied Health', 'Allied Health', 'Allied Health', 'allied_staff', TRUE, NOW(), NOW()),
('tmpl-allied-speech-2', 'allied-health-speech', 'Speech & Language Therapist - Allied Health', 'Allied Health Professional', 'Allied Health', 'Allied Health Professionals', 'staff', TRUE, NOW(), NOW()),
('tmpl-allied-resp-1', 'allied-respiratory', 'Respiratory Therapist', 'Allied Health', 'Allied Health', 'Allied Health', 'allied_staff', TRUE, NOW(), NOW()),
('tmpl-allied-resp-2', 'allied-health-resp', 'Respiratory Therapist - Allied Health', 'Allied Health Professional', 'Allied Health', 'Allied Health Professionals', 'staff', TRUE, NOW(), NOW()),
('tmpl-allied-diet-1', 'allied-dietitian', 'Dietitian', 'Allied Health', 'Allied Health', 'Allied Health', 'allied_diet', TRUE, NOW(), NOW()),
('tmpl-allied-diet-2', 'allied-health-dietitian', 'Dietitian - Allied Health', 'Allied Health Professional', 'Allied Health', 'Allied Health Professionals', 'staff', TRUE, NOW(), NOW()),
('tmpl-allied-nutri-1', 'allied-nutritionist', 'Nutritionist', 'Allied Health', 'Allied Health', 'Allied Health', 'allied_diet', TRUE, NOW(), NOW()),
('tmpl-allied-nutri-2', 'allied-health-nutri', 'Nutritionist - Allied Health', 'Allied Health Professional', 'Allied Health', 'Allied Health Professionals', 'staff', TRUE, NOW(), NOW()),
('tmpl-allied-psych-1', 'allied-psychologist', 'Psychologist', 'Allied Health', 'Allied Health', 'Allied Health', 'allied_psych', TRUE, NOW(), NOW()),
('tmpl-allied-psych-2', 'allied-health-psych', 'Psychologist - Allied Health', 'Allied Health Professional', 'Allied Health', 'Allied Health Professionals', 'staff', TRUE, NOW(), NOW()),
('tmpl-allied-social-1', 'allied-social-worker', 'Social Worker', 'Allied Health', 'Allied Health', 'Allied Health', 'allied_staff', TRUE, NOW(), NOW()),
('tmpl-allied-social-2', 'allied-health-social', 'Social Worker - Allied Health', 'Allied Health Professional', 'Allied Health', 'Allied Health Professionals', 'staff', TRUE, NOW(), NOW()),
('tmpl-allied-couns-1', 'allied-counselor', 'Counselor', 'Allied Health', 'Allied Health', 'Allied Health', 'allied_staff', TRUE, NOW(), NOW()),
('tmpl-allied-couns-2', 'allied-health-couns', 'Counselor - Allied Health', 'Allied Health Professional', 'Allied Health', 'Allied Health Professionals', 'staff', TRUE, NOW(), NOW()),
('tmpl-allied-podi-1', 'allied-podiatrist', 'Podiatrist', 'Allied Health', 'Allied Health', 'Allied Health', 'allied_staff', TRUE, NOW(), NOW()),
('tmpl-allied-podi-2', 'allied-health-podi', 'Podiatrist - Allied Health', 'Allied Health Professional', 'Allied Health', 'Allied Health Professionals', 'staff', TRUE, NOW(), NOW()),
('tmpl-allied-audio-1', 'allied-audiologist', 'Audiologist', 'Allied Health', 'Allied Health', 'Allied Health', 'allied_staff', TRUE, NOW(), NOW()),
('tmpl-allied-audio-2', 'allied-health-audio', 'Audiologist - Allied Health', 'Allied Health Professional', 'Allied Health', 'Allied Health Professionals', 'staff', TRUE, NOW(), NOW()),
('tmpl-allied-opto-1', 'allied-optometrist', 'Optometrist', 'Allied Health', 'Allied Health', 'Allied Health', 'allied_staff', TRUE, NOW(), NOW()),
('tmpl-allied-opto-2', 'allied-health-opto', 'Optometrist - Allied Health', 'Allied Health Professional', 'Allied Health', 'Allied Health Professionals', 'staff', TRUE, NOW(), NOW()),

-- LABORATORY & DIAGNOSTIC STAFF
('tmpl-lab-director', 'diag-lab-director', 'Laboratory Director', 'Diagnostic Staff', 'Diagnostic Staff', 'Laboratory', 'lab_exec', TRUE, NOW(), NOW()),
('tmpl-lab-scientist', 'diag-lab-scientist', 'Medical Laboratory Scientist', 'Diagnostic Staff', 'Diagnostic Staff', 'Laboratory', 'lab_scientist', TRUE, NOW(), NOW()),
('tmpl-lab-tech', 'diag-lab-tech', 'Lab Technician', 'Diagnostic Staff', 'Diagnostic Staff', 'Laboratory', 'lab_technician', TRUE, NOW(), NOW()),
('tmpl-lab-phleb', 'diag-phleb', 'Phlebotomist', 'Diagnostic Staff', 'Diagnostic Staff', 'Laboratory', 'lab_phleb', TRUE, NOW(), NOW()),
('tmpl-diag-radiographer', 'diag-radiographer', 'Radiographer', 'Diagnostic Staff', 'Diagnostic Staff', 'Imaging', 'diag_radiographer', TRUE, NOW(), NOW()),
('tmpl-diag-sonographer', 'diag-sonographer', 'Sonographer (Ultrasound)', 'Diagnostic Staff', 'Diagnostic Staff', 'Imaging', 'diag_radio_tech', TRUE, NOW(), NOW()),
('tmpl-diag-ct-mri', 'diag-imaging-tech', 'CT/MRI Technician', 'Diagnostic Staff', 'Diagnostic Staff', 'Imaging', 'diag_radio_tech', TRUE, NOW(), NOW()),
('tmpl-diag-biomed', 'diag-biomed-eng', 'Biomedical Engineer', 'Diagnostic Staff', 'Diagnostic Staff', 'Engineering', 'it_biomed', TRUE, NOW(), NOW()),
('tmpl-diag-equip', 'diag-equip-tech', 'Medical Equipment Technician', 'Diagnostic Staff', 'Diagnostic Staff', 'Engineering', 'it_biomed', TRUE, NOW(), NOW()),

-- PHARMACY & MEDICATION
('tmpl-pharm-chief', 'pharm-chief', 'Chief Pharmacist', 'Pharmacy Staff', 'Allied Health', 'Pharmacy', 'pharm_lead', TRUE, NOW(), NOW()),
('tmpl-pharm-dispensing', 'pharm-dispensing', 'Dispensing Pharmacist', 'Pharmacy Staff', 'Allied Health', 'Pharmacy', 'pharm_pharmacist', TRUE, NOW(), NOW()),
('tmpl-pharm-inventory', 'pharm-inventory', 'Inventory Pharmacist', 'Pharmacy Staff', 'Allied Health', 'Pharmacy', 'pharm_pharmacist', TRUE, NOW(), NOW()),
('tmpl-pharm-pharmacist', 'allied-pharmacist', 'Pharmacist', 'Pharmacy Staff', 'Allied Health', 'Allied Health', 'pharm_pharmacist', TRUE, NOW(), NOW()),
('tmpl-pharm-clinical', 'allied-clin-pharm', 'Clinical Pharmacist', 'Pharmacy Staff', 'Allied Health', 'Allied Health', 'pharm_pharmacist', TRUE, NOW(), NOW()),
('tmpl-pharm-tech', 'allied-pharm-tech', 'Pharmacy Technician', 'Pharmacy Staff', 'Allied Health', 'Allied Health', 'pharm_tech', TRUE, NOW(), NOW()),
('tmpl-pharm-asst', 'allied-pharm-asst', 'Pharmacy Assistant', 'Pharmacy Staff', 'Allied Health', 'Allied Health', 'pharm_asst', TRUE, NOW(), NOW()),

-- EMERGENCY & CRITICAL CARE
('tmpl-er-physician', 'er-physician', 'Emergency Physician', 'Emergency Staff', 'Clinical Staff', 'Emergency', 'doctor_er', TRUE, NOW(), NOW()),
('tmpl-er-trauma', 'er-trauma-team', 'Trauma Team Member', 'Emergency Staff', 'Clinical Staff', 'Emergency', 'staff_er', TRUE, NOW(), NOW()),
('tmpl-er-paramedic', 'er-paramedic', 'Paramedic', 'Emergency Staff', 'Clinical Staff', 'Emergency', 'staff_paramedic', TRUE, NOW(), NOW()),
('tmpl-er-nurse', 'er-nurse', 'Emergency Nurse', 'Emergency Nursing', 'Nursing Staff', 'Emergency', 'nurse_triage', TRUE, NOW(), NOW()),
('tmpl-er-icu', 'er-icu-staff', 'ICU Staff', 'Emergency Nursing', 'Nursing Staff', 'Emergency', 'nurse_icu', TRUE, NOW(), NOW()),
('tmpl-er-ambulance', 'er-ambulance', 'Ambulance Driver', 'Emergency Support', 'Support Staff', 'Emergency', 'staff_logistics', TRUE, NOW(), NOW()),
('tmpl-er-first-responder', 'er-first-responder', 'First Responder', 'Emergency Support', 'Support Staff', 'Emergency', 'staff_er', TRUE, NOW(), NOW()),

-- INPATIENT / WARD SUPPORT
('tmpl-ward-clerk', 'ward-clerk', 'Ward Clerk', 'Ward Support', 'Support Staff', 'Ward', 'reception_ward', TRUE, NOW(), NOW()),
('tmpl-ward-patient-asst', 'ward-patient-asst', 'Patient Care Assistant', 'Ward Support', 'Support Staff', 'Ward', 'staff_care', TRUE, NOW(), NOW()),
('tmpl-ward-healthcare-asst', 'ward-healthcare-asst', 'Healthcare Assistant', 'Ward Support', 'Support Staff', 'Ward', 'staff_care', TRUE, NOW(), NOW()),
('tmpl-ward-porter', 'ward-porter', 'Porter (Patient Transport)', 'Ward Support', 'Support Staff', 'Ward', 'staff_logistics', TRUE, NOW(), NOW()),
('tmpl-ward-bed-manager', 'ward-bed-manager', 'Bed Manager', 'Ward Administration', 'Administrative Staff', 'Ward', 'admin_ward', TRUE, NOW(), NOW()),
('tmpl-ward-admission', 'ward-admission-coord', 'Admission/Discharge Coordinator', 'Ward Administration', 'Administrative Staff', 'Ward', 'admin_ward', TRUE, NOW(), NOW()),

-- ADMINISTRATION & MANAGEMENT
('tmpl-admin-hospital', 'admin-hospital', 'Hospital Administrator', 'Administrative Staff', 'Administrative Staff', 'Admin', 'admin_manager', TRUE, NOW(), NOW()),
('tmpl-admin-ops', 'admin-ops-manager', 'Operations Manager', 'Administrative Staff', 'Administrative Staff', 'Admin', 'admin_manager', TRUE, NOW(), NOW()),
('tmpl-admin-dept-coord', 'admin-dept-coord', 'Department Coordinator', 'Administrative Staff', 'Administrative Staff', 'Admin', 'admin_staff', TRUE, NOW(), NOW()),
('tmpl-admin-health-info', 'admin-health-info', 'Health Information Manager', 'Administrative Staff', 'Administrative Staff', 'Records', 'admin_records_lead', TRUE, NOW(), NOW()),
('tmpl-admin-records', 'admin-records-off', 'Medical Records Officer', 'Administrative Staff', 'Administrative Staff', 'Records', 'admin_records', TRUE, NOW(), NOW()),
('tmpl-admin-coder', 'admin-coder', 'Medical Coder', 'Administrative Staff', 'Administrative Staff', 'Finance', 'admin_billing', TRUE, NOW(), NOW()),
('tmpl-admin-biller', 'admin-biller', 'Medical Biller', 'Administrative Staff', 'Administrative Staff', 'Finance', 'admin_billing', TRUE, NOW(), NOW()),
('tmpl-admin-accountant', 'admin-accountant', 'Accountant', 'Administrative Staff', 'Administrative Staff', 'Finance', 'admin_finance', TRUE, NOW(), NOW()),
('tmpl-admin-billing-off', 'admin-billing-off', 'Billing Officer', 'Administrative Staff', 'Administrative Staff', 'Finance', 'admin_billing', TRUE, NOW(), NOW()),
('tmpl-admin-insurance', 'admin-insurance', 'Insurance Coordinator', 'Administrative Staff', 'Administrative Staff', 'Finance', 'admin_billing', TRUE, NOW(), NOW()),
('tmpl-admin-hr', 'admin-hr-manager', 'HR Manager', 'Administrative Staff', 'Administrative Staff', 'HR', 'admin_hr', TRUE, NOW(), NOW()),
('tmpl-admin-recruiter', 'admin-recruiter', 'Recruiter', 'Administrative Staff', 'Administrative Staff', 'HR', 'admin_hr', TRUE, NOW(), NOW()),
('tmpl-admin-training', 'admin-training', 'Training Coordinator', 'Administrative Staff', 'Administrative Staff', 'HR', 'admin_hr', TRUE, NOW(), NOW()),

-- IT & DIGITAL HEALTH
('tmpl-it-health-spec', 'it-health-spec', 'Health IT Specialist', 'IT Staff', 'IT & System', 'IT', 'it_staff', TRUE, NOW(), NOW()),
('tmpl-it-emr-admin', 'it-emr-admin', 'EMR/EHR Administrator', 'IT Administration', 'IT & System', 'IT', 'it_admin', TRUE, NOW(), NOW()),
('tmpl-it-sys-admin', 'it-sys-admin', 'System Administrator', 'IT Administration', 'IT & System', 'IT', 'it_admin', TRUE, NOW(), NOW()),
('tmpl-it-db-admin', 'it-db-admin', 'Database Administrator', 'IT Administration', 'IT & System', 'IT', 'it_admin', TRUE, NOW(), NOW()),
('tmpl-it-cyber', 'it-cyber-spec', 'Cybersecurity Specialist', 'IT Staff', 'IT & System', 'IT', 'it_security', TRUE, NOW(), NOW()),
('tmpl-it-data', 'it-data-analyst', 'Data Analyst (Healthcare)', 'IT Staff', 'IT & System', 'IT', 'it_data', TRUE, NOW(), NOW()),
('tmpl-it-ai', 'it-ai-engineer', 'AI/Clinical Decision Support Engineer', 'IT Staff', 'IT & System', 'IT', 'it_ai_eng', TRUE, NOW(), NOW()),

-- SUPPORT & FACILITY
('tmpl-support-housekeeping', 'support-housekeeping', 'Cleaner / Housekeeping Staff', 'Support Staff', 'Support Staff', 'Facility', 'staff_support', TRUE, NOW(), NOW()),
('tmpl-support-infection', 'support-infection', 'Infection Control Staff', 'Support Staff', 'Support Staff', 'Facility', 'staff_support', TRUE, NOW(), NOW()),
('tmpl-support-waste', 'support-waste', 'Waste Management Staff', 'Support Staff', 'Support Staff', 'Facility', 'staff_support', TRUE, NOW(), NOW()),
('tmpl-support-kitchen', 'support-kitchen', 'Kitchen Staff', 'Support Staff', 'Support Staff', 'Hospitality', 'staff_support', TRUE, NOW(), NOW()),
('tmpl-support-diet', 'support-diet-asst', 'Diet Kitchen Assistant', 'Support Staff', 'Support Staff', 'Hospitality', 'staff_support', TRUE, NOW(), NOW()),
('tmpl-support-food', 'support-food-worker', 'Food Service Worker', 'Support Staff', 'Support Staff', 'Hospitality', 'staff_support', TRUE, NOW(), NOW()),
('tmpl-support-security', 'support-security', 'Security Guard', 'Support Staff', 'Support Staff', 'Security', 'staff_security', TRUE, NOW(), NOW()),
('tmpl-support-safety', 'support-safety', 'Safety Officer', 'Support Staff', 'Support Staff', 'Security', 'staff_security', TRUE, NOW(), NOW()),
('tmpl-support-store', 'support-store-mgr', 'Store Manager', 'Support Staff', 'Support Staff', 'Logistics', 'staff_logistics', TRUE, NOW(), NOW()),
('tmpl-support-inventory', 'support-inventory', 'Inventory Manager', 'Support Staff', 'Support Staff', 'Logistics', 'staff_logistics', TRUE, NOW(), NOW()),
('tmpl-support-supply', 'support-supply', 'Supply Chain Officer', 'Support Staff', 'Support Staff', 'Logistics', 'staff_logistics', TRUE, NOW(), NOW()),

-- COMMUNITY & OUTREACH
('tmpl-comm-health-worker', 'comm-health-worker', 'Community Health Worker', 'Community Staff', 'External / Community', 'Outreach', 'comm_worker', TRUE, NOW(), NOW()),
('tmpl-comm-extension', 'comm-extension', 'Health Extension Worker', 'Community Staff', 'External / Community', 'Outreach', 'comm_extension', TRUE, NOW(), NOW()),
('tmpl-comm-coord', 'comm-outreach-coord', 'Outreach Coordinator', 'Community Staff', 'External / Community', 'Outreach', 'comm_worker', TRUE, NOW(), NOW()),
('tmpl-comm-public-health', 'comm-public-health', 'Public Health Officer', 'Community Staff', 'External / Community', 'Outreach', 'comm_lead', TRUE, NOW(), NOW()),
('tmpl-comm-epidemiologist', 'comm-epidemiologist', 'Epidemiologist', 'Community Staff', 'External / Community', 'Outreach', 'comm_lead', TRUE, NOW(), NOW()),

-- EDUCATION & RESEARCH
('tmpl-edu-medical', 'edu-medical', 'Medical Educator', 'Education Staff', 'Clinical Staff', 'Academic', 'doctor_edu', TRUE, NOW(), NOW()),
('tmpl-edu-trainer', 'edu-clin-trainer', 'Clinical Trainer', 'Education Staff', 'Clinical Staff', 'Academic', 'staff_edu', TRUE, NOW(), NOW()),
('tmpl-res-scientist', 'res-scientist', 'Research Scientist', 'Research Staff', 'Clinical Staff', 'Research', 'staff_research', TRUE, NOW(), NOW()),
('tmpl-res-trial', 'res-trial-coord', 'Clinical Trial Coordinator', 'Research Staff', 'Clinical Staff', 'Research', 'staff_research', TRUE, NOW(), NOW()),
('tmpl-res-academic', 'res-academic', 'Academic Staff', 'Education Staff', 'Clinical Staff', 'Academic', 'staff_edu', TRUE, NOW(), NOW()),

-- LEGAL & COMPLIANCE
('tmpl-legal-advisor', 'legal-advisor', 'Legal Advisor', 'Legal Staff', 'Administrative Staff', 'Legal', 'admin_legal', TRUE, NOW(), NOW()),
('tmpl-legal-compliance', 'legal-compliance', 'Compliance Officer', 'Legal Staff', 'Administrative Staff', 'Legal', 'admin_legal', TRUE, NOW(), NOW()),
('tmpl-legal-risk', 'legal-risk-mgr', 'Risk Manager', 'Legal Staff', 'Administrative Staff', 'Legal', 'admin_legal', TRUE, NOW(), NOW()),
('tmpl-legal-ethics', 'legal-ethics-comm', 'Ethics Committee Member', 'Legal Staff', 'Administrative Staff', 'Legal', 'admin_legal', TRUE, NOW(), NOW())

ON CONFLICT (template_key) DO UPDATE SET active = TRUE, updated_at = NOW();
